-불린 마스크
조건절의 결과는 True, False로 반환
True인 결과의 데이터프레임 반환

넘파이배열[조건절]
==, !=, <=, >=
&, |, ~

In [2]:
import numpy as np

In [2]:
matrix = np.arange(1, 21)
matrix

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [3]:
#넘파이 배열에 비교 연산자 적용 -> True/ False 값 반환
matrix > 10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [5]:
#True 반환값의 갯수
(matrix > 10).sum()

10

In [6]:
#넘파이 배열[조건절] -> 조건절을 만족하는 실제 값 반환
matrix[matrix > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
#퀴즈 : 1-100 사이의 숫자 중에 30개를 추출해서 랜덤하게 넘파이 배열을 생성하고
#30보다 크거나 70보다 작은 숫자를 출력하라
#n > 30 ? n < 70

In [7]:
matrix1 = np.random.randint(1, 101, 30)
matrix1

array([17, 48,  7, 99, 74, 10, 46, 51, 91, 78, 54, 76, 44, 70,  7, 11, 86,
       89,  7, 10, 16,  5, 14,  4, 12, 51, 51, 51, 36, 11])

In [16]:
# 30 < n < 70
(matrix1 > 30) & (matrix1 < 70)

array([False,  True, False, False, False, False,  True,  True, False,
       False,  True, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
        True,  True, False])

In [17]:
((matrix1 > 30) & (matrix1 < 70)).sum()

9

In [18]:
matrix1[(matrix1 > 30) & (matrix1 < 70)]

array([48, 46, 51, 54, 44, 51, 51, 51, 36])

In [19]:
# (n < 10) or (n > 90)
matrix1[(matrix1 < 10) | (matrix1 > 90)]

array([ 7, 99, 91,  7,  7,  5,  4])

In [20]:
# not ~ -> 10 <= n <= 90
matrix1[~((matrix1 < 10) | (matrix1 > 90))]

array([17, 48, 74, 10, 46, 51, 78, 54, 76, 44, 70, 11, 86, 89, 10, 16, 14,
       12, 51, 51, 51, 36, 11])

-팬시 인덱싱

넘파이배열1[넘파이배열2]
넘파이배열2 -> 인덱스 역할

In [22]:
matrix2 = np.random.randint(1, 100, 30)
matrix2

array([97, 93, 33, 29, 15, 61, 99, 23, 13,  1, 21, 64, 56, 71, 95, 11, 30,
       53, 58, 33, 66, 68, 94, 82, 26, 76, 83,  4, 26, 25])

In [27]:
#필터링 인덱스 -> 팬시 인덱싱
#정수 형태여야 함

matrix3 = np.array([0, 0, 0, 2, 3, 10, 20, -1])
matrix3

array([ 0,  0,  0,  2,  3, 10, 20, -1])

In [28]:
matrix2[matrix3]

array([97, 97, 97, 33, 29, 21, 66, 25])

In [29]:
matrix4 = np.random.randint(1, 100, 30).reshape(6, 5)
matrix4

array([[ 2, 79, 44, 12, 46],
       [65, 68, 53, 44, 67],
       [75, 31, 74, 65, 35],
       [60, 15, 36, 91, 54],
       [33, 99, 35, 68, 64],
       [42, 79, 69, 30, 38]])

In [30]:
matrix4[0][0], matrix4[0][0]

(2, 2)

In [31]:
#matrix4에서 1행 1열 값과 6행 5열 값을 추출
matrix4[5, 4], matrix4[-1, -1]

(38, 38)

In [34]:
matrix5 = [0, 1]
matrix6 = [[0, 0], [1, 1], [3, 2]]

In [35]:
matrix4

array([[ 2, 79, 44, 12, 46],
       [65, 68, 53, 44, 67],
       [75, 31, 74, 65, 35],
       [60, 15, 36, 91, 54],
       [33, 99, 35, 68, 64],
       [42, 79, 69, 30, 38]])

In [36]:
#1, 2행 출력
matrix4[matrix5]

array([[ 2, 79, 44, 12, 46],
       [65, 68, 53, 44, 67]])

In [37]:
matrix4[[0, 1, 2], [0]]

array([ 2, 65, 75])

In [38]:
# 배열이름[ [i1, i2, i3 ... ], [j1, j2, j3 ... ]]
# [i1,j1], [i2,j2] ... 
# 대각선의 값만 출력
matrix4[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]

array([ 2, 68, 74, 91, 64])

In [40]:
matrix4[[0, 1, 2], 0:2]

array([[ 2, 79],
       [65, 68],
       [75, 31]])

In [41]:
matrix4 = np.arange(1,26).reshape(5,5)
matrix4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [42]:
# 방법1
matrix4[0,0], matrix4[1,1], matrix4[2,2], matrix4[3,3], matrix4[4,4]

(1, 7, 13, 19, 25)

In [43]:
# 방법2
for i in range(len(matrix4)):
    print(matrix4[i, i], end='\t')

1	7	13	19	25	

In [44]:
# 방법3 - 팬시인덱싱 
matrix4[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]

array([ 1,  7, 13, 19, 25])

In [45]:
# 방법4
# 별도 배열로 정의할려면 모두 튜플이나 리스트로 정의 
# fancy = ((0, 1, 2, 3, 4), (0, 1, 2, 3, 4))
fancy = [[0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]
matrix4[fancy]

<ipython-input-45-3918f182cc89>:5: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  matrix4[fancy]


array([ 1,  7, 13, 19, 25])

-np.where()를 이용한 필터링

np.where(조건식) -> 조건식을 만족하는 인덱스 반환
np.where(조건식, T, F) -> 조건식을 만족하면 T값, 그렇지 않다면 F값
배열 [np.where(조건식)] -> 조건식을 만족하는 실제 배열값이 반환 

In [46]:
a = np.arange(10)
np.where(a < 5, a, 10*a)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [48]:
a = np.arange(20, 31)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [49]:
#조건식을 만족하는 인덱스 반환
np.where(a < 25)

(array([0, 1, 2, 3, 4], dtype=int64),)

In [50]:
#조건식을 만족하면 현재값 유지, 그렇지 않다면 10을 곱함
np.where(a < 25, a, 10*a)

array([ 20,  21,  22,  23,  24, 250, 260, 270, 280, 290, 300])

In [52]:
np.where(a < 25, 1, 0)

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0])

In [51]:
#조건식을 만족하는 배열의 실제값 반환
a[np.where(a < 25)]

array([20, 21, 22, 23, 24])

In [53]:
#중복값 없이 뽑기
arr = np.random.choice(10, 8, replace=False)
arr

array([5, 8, 7, 0, 3, 6, 4, 1])

In [56]:
ls

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: E070-A7AC

 C:\numpy\data 디렉터리

2021-11-24  오후 01:41    <DIR>          .
2021-11-24  오후 01:41    <DIR>          ..
2021-11-24  오전 09:41    <DIR>          .ipynb_checkpoints
2021-11-23  오후 05:47            77,056 211123.ipynb
2021-11-24  오후 01:41            18,445 211124.ipynb
2021-11-23  오전 12:12             3,088 births.txt
2021-11-23  오전 12:25            35,455 Jeju2021.csv
2016-07-17  오후 09:46           171,308 movies.dat
2021-11-24  오전 09:15            15,388 Numpy_Quiz.ipynb
2018-04-24  오전 10:42        24,594,131 ratings.dat
2019-03-20  오전 10:54         1,185,149 seoul.csv
2021-01-31  오후 08:49            93,805 seoul2021.csv
               9개 파일          26,193,825 바이트
               3개 디렉터리  454,228,602,880 바이트 남음


-외부 파일 연동

배열명 = np.loadtxt('파일경로', delimiter='구분자', dtype=데이터형)

In [80]:
# rating.dat 로딩 
rating = np.loadtxt('ratings.dat', delimiter='::', dtype=int)

In [73]:
rating.shape, rating.ndim, rating.dtype

((1000209, 4), 2, dtype('int32'))

In [74]:
# 3개만 출력 
rating[:3, :]

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968]])

In [75]:
# 3열이 평점 
# 3열의 평점의 평균은?
rating[:, 2].mean()

3.581564453029317

In [81]:
# 중복값 없이 배열값 표시 
np.unique?

In [77]:
# 퀴즈 : 
# 1) userId가 2인 배열값만 출력?
# 2) userId가 2인 사람의 평점의 평균은?

In [84]:
rating[rating[:,0] == 2]

array([[        2,      1357,         5, 978298709],
       [        2,      3068,         4, 978299000],
       [        2,      1537,         4, 978299620],
       [        2,       647,         3, 978299351],
       [        2,      2194,         4, 978299297],
       [        2,       648,         4, 978299913],
       [        2,      2268,         5, 978299297],
       [        2,      2628,         3, 978300051],
       [        2,      1103,         3, 978298905],
       [        2,      2916,         3, 978299809],
       [        2,      3468,         5, 978298542],
       [        2,      1210,         4, 978298151],
       [        2,      1792,         3, 978299941],
       [        2,      1687,         3, 978300174],
       [        2,      1213,         2, 978298458],
       [        2,      3578,         5, 978298958],
       [        2,      2881,         3, 978300002],
       [        2,      3030,         4, 978298434],
       [        2,      1217,         3, 97829

In [85]:
user2 = rating[rating[:,0] == 2]
user2[:5, :]

array([[        2,      1357,         5, 978298709],
       [        2,      3068,         4, 978299000],
       [        2,      1537,         4, 978299620],
       [        2,       647,         3, 978299351],
       [        2,      2194,         4, 978299297]])

In [86]:
f'user id 가 2인 사람의 평점의 평균은? {user2[:, 2].mean():.2f}'

'user id 가 2인 사람의 평점의 평균은? 3.71'

f' 문자열 ...{변수:포맷팅} ...'  -> 파이썬 3. 6 이상부터 지원

-np.savetxt

파일 저장)
np.savetxt('파일경로', 배열이름, fmt='포맷형식', delimiter='구분자')

In [87]:
#100개의 데이터만 output 폴더 안에 csv 파일 형태로 저장하기
rating100 = rating[:100, :]
len(rating100)

100

In [88]:
import os

try:
    # 현재 폴더를 기준으로 폴더 생성 
    os.mkdir('output')
except:
    print('폴더가 이미 생성되었어요 !!! ')

In [89]:
ls

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: E070-A7AC

 C:\numpy\data 디렉터리

2021-11-24  오후 02:29    <DIR>          .
2021-11-24  오후 02:29    <DIR>          ..
2021-11-24  오전 09:41    <DIR>          .ipynb_checkpoints
2021-11-23  오후 05:47            77,056 211123.ipynb
2021-11-24  오후 02:29            33,294 211124.ipynb
2021-11-23  오전 12:12             3,088 births.txt
2021-11-23  오전 12:25            35,455 Jeju2021.csv
2016-07-17  오후 09:46           171,308 movies.dat
2021-11-24  오전 09:15            15,388 Numpy_Quiz.ipynb
2021-11-24  오후 02:29    <DIR>          output
2018-04-24  오전 10:42        24,594,131 ratings.dat
2019-03-20  오전 10:54         1,185,149 seoul.csv
2021-01-31  오후 08:49            93,805 seoul2021.csv
               9개 파일          26,208,674 바이트
               4개 디렉터리  454,222,753,792 바이트 남음


In [90]:
np.savetxt('output/rating100.csv', rating100, delimiter=',')

In [91]:
ls output

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: E070-A7AC

 C:\numpy\data\output 디렉터리

2021-11-24  오후 02:33    <DIR>          .
2021-11-24  오후 02:33    <DIR>          ..
2021-11-24  오후 02:33            10,100 rating100.csv
               1개 파일              10,100 바이트
               2개 디렉터리  454,222,348,288 바이트 남음


In [92]:
# np.savetxt('output/rating100.csv', rating100, delimiter=',', fmt='%.2f')
np.savetxt('output/rating100.csv', rating100, delimiter=',', fmt='%d')

pandas

In [4]:
import pandas as pd

In [94]:
pd.__version__

'1.2.4'

-pandas 자료 구조

넘파이 < 시리즈 < 데이터프레임
시리즈
데이터프레임

-시리즈(Series)
: 리스트와 딕셔너리 두가지의 장점을 섞어놓은 듯한 자료구조
리스트나 튜플처럼 숫자인덱싱
딕셔너리와 같이 키인덱싱

pd.Series(data=리스트/튜플/넘파이배열/딕셔너리, index=인덱스리스트)

In [96]:
pd.Series?

In [102]:
#딕셔너리 -> 시리즈
mydict = {'a':1, 'b':2, 'c':3, 'd':4, 'e':5}
s1 = pd.Series(data=mydict)
s1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [99]:
type(s1)

pandas.core.series.Series

In [100]:
len(s1)

3

In [104]:
#인덱싱
s1['a'], s1[0], s1[-1]

(1, 1, 5)

In [107]:
#슬라이싱
print(s1[:2])
print()
print(s1['a':'c'])
print()
print(s1[::2])
print()
print(s1[::-1])
print()
# 불연속인 데이타 출력 
# 시리즈명[[인덱스1, 인덱스2 .... ]]
print(s1[[0,3,0, 1]])

a    1
b    2
dtype: int64

a    1
b    2
c    3
dtype: int64

a    1
c    3
e    5
dtype: int64

e    5
d    4
c    3
b    2
a    1
dtype: int64

a    1
d    4
a    1
b    2
dtype: int64


In [108]:
#넘파이배열 -> 시리즈
matrix = np.arange(10, 0, -1)
matrix

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [109]:
s2 = pd.Series(data=matrix)
s2

0    10
1     9
2     8
3     7
4     6
5     5
6     4
7     3
8     2
9     1
dtype: int32

In [112]:
np.sum(s2), np.mean(s2), np.median(s2), np.min(s2), np.max(s2)

(55, 5.5, 5.5, 1, 10)

In [113]:
#튜플 -> 시리즈
# 시리즈의 데이터형은 혼합형이 가능하다. 
# 혼합형은 object
myTuple = ('가', '나', True, 100, 3.14)
myTuple

('가', '나', True, 100, 3.14)

In [114]:
s3 = pd.Series(data=myTuple)
s3

0       가
1       나
2    True
3     100
4    3.14
dtype: object

In [117]:
type(s3[1]), type(s3[2]), type(s3[3])

(str, bool, int)

In [118]:
s3.dtype, s3.values, s3.index

(dtype('O'),
 array(['가', '나', True, 100, 3.14], dtype=object),
 RangeIndex(start=0, stop=5, step=1))

-시리즈 속성
dtype : 데이터형 확인
values : 값만 넘파이배열 형태로 출력
index : 시리즈의 인덱스값만 리스트 형태로 출력

In [119]:
list(s1.index), tuple(s1.index)

(['a', 'b', 'c', 'd', 'e'], ('a', 'b', 'c', 'd', 'e'))

-인덱스 이름, 시리즈 이름 지정

시리즈명.index.name=인덱스이름
시리즈명.name=시리즈이름
시리즈명.index=리스트

In [126]:
#딕셔너리 -> 시리즈
sdata = {"Charles": 35000, "Julia":71000, "Hayoung":16000, "Sangjae":5000}
s4 = pd.Series(sdata, name="보너스")
s4.index.name="회원"
s4

회원
Charles    35000
Julia      71000
Hayoung    16000
Sangjae     5000
Name: 보너스, dtype: int64

In [127]:
s4.name = "상여금"
s4

회원
Charles    35000
Julia      71000
Hayoung    16000
Sangjae     5000
Name: 상여금, dtype: int64

In [130]:
#리스트 -> 시리즈
#인덱스명은 별도 설정
myList = ['라면', '짜장면','짬뽕','로제떡볶이']
s5 = pd.Series(myList, index=['메뉴1', '메뉴2', '메뉴3', '메뉴4'])
s5

메뉴1       라면
메뉴2      짜장면
메뉴3       짬뽕
메뉴4    로제떡볶이
dtype: object

In [131]:
s5['메뉴3']

'짬뽕'

Quiz 1
1) 딕셔너리 생성 
   {'a': 'apart', 'b': 'banana', 'c': 'cat'}
2) 리스트 생성 
  ['아파트', '바나나', '고양이']
3) 1번의 키값 + 2번의 데이타 => 시리즈생성 
  'a'   '아파트'
  'b'   '바나나'
  'c'   '고양이'
Quiz 2
아래와 같은 형태로 시리즈를 생성하고 평균값을 출력하여라

과목 
---------
국어    90
수학    80
영어    100
과학    55
역사    70 
Name:중간고사성적표, dtype=?
---------
평균 = ?

In [6]:
dic = {'a': 'apart', 'b': 'banana', 'c': 'cat'}
dic

{'a': 'apart', 'b': 'banana', 'c': 'cat'}

In [7]:
list = ['아파트', '바나나', '고양이']
list

['아파트', '바나나', '고양이']

In [8]:
s6 = pd.Series(list, index=dic.keys())
s6

a    아파트
b    바나나
c    고양이
dtype: object

In [141]:
sb = {"국어": 90, "수학":80, "영어":100, "과학":55, "역사": 70}
s7 = pd.Series(sb, name="중간고사성적표")
s7.index.name="과목"
print("-"*10)
print(s7)
print("-"*10)
print("평균 :", sum(s7[:])/len(s7))

----------
과목
국어     90
수학     80
영어    100
과학     55
역사     70
Name: 중간고사성적표, dtype: int64
----------
평균 : 79.0


In [9]:
score = {'국어':90,'수학':80,'영어':100,'과학':55,'역사':70}
pd_ave = pd.Series(score)
pd_ave.name = '중간고사성적표'
pd_ave.index.name = '과목'
# ave=0
# for i in pd_ave:
#     ave = ave + i
print(pd_ave)
print("---------")
# print("평균 =",ave/len(pd_ave))
print("평균 =", pd_ave.mean())

과목
국어     90
수학     80
영어    100
과학     55
역사     70
Name: 중간고사성적표, dtype: int64
---------
평균 = 79.0
