In [ ]:
ls

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: E070-A7AC

 C:\numpy\data 디렉터리

2021-11-23  오전 10:15    <DIR>          .
2021-11-23  오전 10:15    <DIR>          ..
2021-11-23  오전 10:15    <DIR>          .ipynb_checkpoints
2021-11-23  오전 10:15                72 211123.ipynb
2021-11-23  오전 12:12             3,088 births.txt
2021-11-23  오전 12:25            35,455 Jeju2021.csv
2016-07-17  오후 09:46           171,308 movies.dat
2018-04-24  오전 10:42        24,594,131 ratings.dat
2019-03-20  오전 10:54         1,185,149 seoul.csv
2021-01-31  오후 08:49            93,805 seoul2021.csv
               7개 파일          26,083,008 바이트
               3개 디렉터리  454,343,933,952 바이트 남음


In [ ]:
# 쥬피터노트북 셀 스타일 조절 
from IPython.core.display import display, HTML
#display(HTML("<style>.container { font-weight: bold !important; }</style>"))
display(HTML("<style>.container { width: 100% !important; }</style>"))

import warnings
warnings.filterwarnings(action='ignore')

In [1]:
import numpy as np

In [ ]:
np.__version__

'1.20.1'

In [ ]:
#메소드와 속성 확인
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__sp

In [ ]:
#명령어 확인
np.mean?

-넘파이 배열 생성

리스트 -> 넘파이
np.array(리스트)

관련 속성
ndim : 차원 반환 -> int
size : 전체 길이 반환 -> int
shape : 구조 반환 -> tuple

In [ ]:
#1차원 리스트 -> 1차원 넘파이

myList = [10, 56, 77, 23, 44]
print(myList, type(myList), len(myList))

[10, 56, 77, 23, 44] <class 'list'> 5


In [ ]:
myArr = np.array(myList)
print(myArr, type(myArr), len(myArr))
print(f' 차원은? {myArr.ndim}')
print(f' 구조는? {myArr.shape}, {type(myArr.shape)}')
print(f' 길이는? {myArr.size}')

[10 56 77 23 44] <class 'numpy.ndarray'> 5
 차원은? 1
 구조는? (5,), <class 'tuple'>
 길이는? 5


In [ ]:
myArr

array([10, 56, 77, 23, 44])

In [ ]:
#2차원 리스트 -> 넘파이

myList2 = [[1, 2, 3],[10, 20, 30],[100, 200, 300]]
myList2

[[1, 2, 3], [10, 20, 30], [100, 200, 300]]

In [ ]:
myArr2 = np.array(myList2)
print(myArr2, type(myArr2), len(myArr2))
print(f' 차원은? {myArr2.ndim}')
print(f' 구조는? {myArr2.shape}, {type(myArr2.shape)}')
print(f' 길이는? {myArr2.size}')
print(f' 넘파이 배열은? {myArr2.shape[0]} 행 {myArr2.shape[1]} 열')

[[  1   2   3]
 [ 10  20  30]
 [100 200 300]] <class 'numpy.ndarray'> 3
 차원은? 2
 구조는? (3, 3), <class 'tuple'>
 길이는? 9
 넘파이 배열은? 3 행 3 열


In [ ]:
myArr2

array([[  1,   2,   3],
       [ 10,  20,  30],
       [100, 200, 300]])

In [ ]:
#2차원 리스트에서 각 행 수가 다른 경우 테스트
#넘파이 배열은?

myList3 = [[1, 2], [10, 20, 30], [100, 200, 300, 400, 500]]
print(myList3)

[[1, 2], [10, 20, 30], [100, 200, 300, 400, 500]]


In [ ]:
#각 행의 개수가 다른 경우 넘파이 배열로 생성하면 list([값...]) 형태로 삽입됨

myArr3= np.array(myList3)
print(myArr3, type(myArr3), len(myArr3))

[list([1, 2]) list([10, 20, 30]) list([100, 200, 300, 400, 500])] <class 'numpy.ndarray'> 3


-넘파이 배열과 리스트와의 차이점

연산 가능
넘파이에서 지원되는 메서드 사용 가능 : 평균, 상관계수, 분산, 표준편차, 최빈값
배열간의 연산도 가능
리스트는 자료형 혼합 가능/ 넘파이 배열은 하나의 자료형만 가능

In [ ]:
#리스트의 경우 +, *
listA = [10, 40, 50]
listB = [10, 40, 50]
# +인 경우 리스트간의 연결
listA + listB

[10, 40, 50, 10, 40, 50]

In [ ]:
#리스트의 경우 * : 리스트의 반복
listA * 2

[10, 40, 50, 10, 40, 50]

In [ ]:
arrA = np.array([10, 40, 50])
arrB = np.array([5, 4, 3])
print(arrA + arrB)
print(arrA - arrB)
print(arrA * arrB)
print(arrA / arrB)
print(arrA // arrB)
print(arrA % arrB)

[15 44 53]
[ 5 36 47]
[ 50 160 150]
[ 2.         10.         16.66666667]
[ 2 10 16]
[0 0 2]


In [ ]:
#브로드캐스팅
#넘파이 배열 연산자 숫자
#넘파이 배열 각각에 연산이 적용됨
print(arrA)
print(arrA * 2)
print(arrA // 3)

[10 40 50]
[ 20  80 100]
[ 3 13 16]


In [ ]:
#리스트와 넘파이 배열의 자료형 테스트
myList_c = ['홍길동', 100, 3.14, True, False]
myList_c, type(myList_c)

(['홍길동', 100, 3.14, True, False], list)

In [ ]:
#넘파이 배열의 구성 요소의 자료형 확인은?
#넘파이배열명.dtype

#데이터가 혼합되어있는 경우 자동 형변환이 됨
myArr_c = np.array(['홍길동', 100, 3.14, True, False])
myArr_c, type(myArr_c), myArr_c.dtype

(array(['홍길동', '100', '3.14', 'True', 'False'], dtype='<U32'),
 numpy.ndarray,
 dtype('<U32'))

In [ ]:
#정수와 실수가 혼합된 넘파이 배열 생성
myArr_d = np.array([100, 3.14, 23.5, 0])
myArr_d, type(myArr_d), myArr_d.dtype

(array([100.  ,   3.14,  23.5 ,   0.  ]), numpy.ndarray, dtype('float64'))

In [ ]:
#통계함수 적용하기
#np.통계함수명(넘파이배열명)
myArr_d

array([100.  ,   3.14,  23.5 ,   0.  ])

In [ ]:
print(f' 배열의 모든합은? {np.sum(myArr_d)}  {myArr_d.sum()}')
print(f' 배열의 평균은? {np.mean(myArr_d)}  {myArr_d.mean()}')
print(f' 배열의 최댓값은? {np.max(myArr_d)}  {myArr_d.max()}')
print(f' 배열의 최솟값은? {np.min(myArr_d)}  {myArr_d.min()}')

 배열의 모든합은? 126.64  126.64
 배열의 평균은? 31.66  31.66
 배열의 최댓값은? 100.0  100.0
 배열의 최솟값은? 0.0  0.0


In [ ]:
print(f' 배열의 중앙값은? {np.median(myArr_d)}')

 배열의 중앙값은? 13.32


In [ ]:
#넘파이 제공 함수를 이용해서 배열 생성하기

np.ones(n), np.ones((x, y))
np.zeros(n), np.zeros((x, y))
np.empty(n), np.empty((x, y))
np.arange(start, end, step)

#1차원 -> 2차원
reshape(x, y)
#2차원 -> 1차원
flatten()

In [ ]:
#1로 구성된 넘파이 배열 -> 실수형
arr1 = np.ones(10)
arr1, arr1.dtype

(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]), dtype('float64'))

In [ ]:
#1로 구성된 넘파이 배열 -> 정수형
arr2 = np.ones(10, dtype=int)
arr2, arr2.dtype

(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]), dtype('int32'))

In [ ]:
# 1 로 구성된 5행 2열 배열 생성 => 정수형 
arr3 = np.ones((5,2), dtype=int)
arr3, arr3.dtype, arr3.shape

(array([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]),
 dtype('int32'),
 (5, 2))

In [ ]:
#3행 3열로 구성된 넘파이 배열
print( np.array([[0,0,0], [0,0,0], [0,0,0]]) )
arr4 = np.zeros((3,3), dtype=int)
print('='*30)
print(arr4)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
#5행 5열로 구성된 넘파이 배열
arr5 = np.empty((5, 5))
arr5

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        1.02360324e-306, 1.22383731e-307],
       [7.56587585e-307, 1.37961302e-306, 1.05699242e-307,
        8.01097889e-307, 1.78020169e-306],
       [7.56601165e-307, 1.02359984e-306, 1.33510679e-306,
        2.22522597e-306, 1.78019761e-306],
       [1.37962185e-306, 1.78019625e-306, 6.89812281e-307,
        9.34609790e-307, 1.24610723e-306],
       [1.05700515e-307, 1.11261774e-306, 1.29060871e-306,
        8.34424766e-308, 2.12203497e-312]])

In [ ]:
#1 - 20으로 구성된 4행 5열의 넘파이 배열

# range() 객체 => 리스트화 list(range()) => 넘파이 배열화 np.array(list(range()))
print(range(1,21), list(range(1,21)))
print(np.array(list(range(1,21))))
print('='*30)
# reshape(x, y) => x행 y열 로 재구성 
arr6 = np.arange(1, 21).reshape(4, 5)
arr6

range(1, 21) [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
# 0 - 49까지 구성된 넘파이 배열
#초기값이 0인 경우 생략 가능
arr7 = np.arange(50)
print(arr7, len(arr7), arr7.size)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49] 50 50


In [ ]:
#원본 넘파이 배열에 다시 적용
arr7 = arr7.reshape(10, 5)
arr7

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [ ]:
#2차원 -> 2차원 변경 가능
arr7.reshape(5, 10)
arr8 = arr7.reshape(5, 10)
arr8

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
#2차원 -> 1차원으로 변경
#넘파이배열.flatten()
arr8.ndim, arr8.shape

(2, (5, 10))

In [ ]:
arr9 = arr8.flatten()
arr9

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
# 0-100 사이의 수 중 짝수로 된 넘파이 배열 생성
arr10 = np.arange(0, 101, 2)
arr10

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [ ]:
#홀수는?
np.arange(1, 101, 2).reshape(25, 2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19],
       [21, 23],
       [25, 27],
       [29, 31],
       [33, 35],
       [37, 39],
       [41, 43],
       [45, 47],
       [49, 51],
       [53, 55],
       [57, 59],
       [61, 63],
       [65, 67],
       [69, 71],
       [73, 75],
       [77, 79],
       [81, 83],
       [85, 87],
       [89, 91],
       [93, 95],
       [97, 99]])

In [ ]:
arr11 = np.arange(1, 31)
arr11, arr11.ndim

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]),
 1)

In [ ]:
#reshape(-1, n) -> 2차원 n개의 컬럼으로 구성
arr12 = arr11.reshape(-1, 1)
arr12, arr12.ndim

(array([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29],
        [30]]),
 2)

In [ ]:
np.arange(1, 21).reshape(-1, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

넘파이 배열의 자료형 형변환

배열명2 = 배열명1.astype(자료형)
자료형 = np.float64, np.int32```

In [ ]:
#정수형, 3행 3열
matrix = np.arange(1, 10).reshape(3, 3)
matrix, matrix.dtype

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 dtype('int32'))

In [ ]:
#실수형, 3행 3열
matrix = np.arange(1,10, dtype=float).reshape(3,3)
matrix, matrix.dtype

(array([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]),
 dtype('float64'))

In [ ]:
#문자열형, 3행 3열
matrix = np.arange(1,10).reshape(3,3)
matrix, matrix.dtype

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 dtype('int32'))

In [ ]:
matrix.astype('<U5')

array([['1', '2', '3'],
       ['4', '5', '6'],
       ['7', '8', '9']], dtype='<U5')

In [ ]:
#논리형으로 구성된 넘파이 배열 생성
matrix2 = np.array([True, False, True, True, False])
matrix2, matrix2.dtype

(array([ True, False,  True,  True, False]), dtype('bool'))

In [ ]:
matrix2.astype(int)

array([1, 0, 1, 1, 0])

In [ ]:
matrix2.astype('<U5')

array(['True', 'False', 'True', 'True', 'False'], dtype='<U5')

In [ ]:
#문자열 숫자 -> 정수나 실수
matrix3 = np.array(['3.14', '5.5', '0.78'])
matrix3

array(['3.14', '5.5', '0.78'], dtype='<U4')

In [ ]:
matrix3.astype(float)

array([3.14, 5.5 , 0.78])

In [ ]:
matrix3.astype(int)
#ValueError

ValueError: invalid literal for int() with base 10: '3.14'

In [ ]:
matrix3.astype(bool)
#ValueError

ValueError: invalid literal for int() with base 10: '3.14'

In [ ]:
matrix4 = np.array(['3', '5', '0'])
matrix4

array(['3', '5', '0'], dtype='<U1')

In [ ]:
matrix4.astype(float)

array([3., 5., 0.])

In [ ]:
matrix4.astype(int)

array([3, 5, 0])

In [ ]:
matrix4.astype(bool)

array([ True,  True, False])

-넘파이 배열의 인덱싱

넘파이배열명[index]
넘파이배열명[i, j] =  넘파이배열명[i][j] -> i행 j열

In [ ]:
matrix_a = np.arange(10)
matrix_b = np.arange(12).reshape(3, 4)

In [ ]:
matrix_a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
matrix_b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#첫 요소와 마지막 요소
matrix_a[0], matrix_a[-1]

(0, 9)

In [ ]:
#2차원에서 1행 1열
matrix_b[0, 0], matrix_b[0][0]

(0, 0)

In [ ]:
#2차원에서 마지막 행의 마지막 열
matrix_b[-1, -1], matrix_b[-1][-1], matrix_b[2][3]

(11, 11, 11)

In [ ]:
#matrix_b에서 3행 1열의 값을 100으로 교체하라
matrix_b[2, 0] = 100

In [ ]:
matrix_b

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [100,   9,  10,  11]])

-넘파이 배열의 슬라이싱 1 : 1차원

넘파이배열명[start:end:step]
넘파이배열명[start:end]
넘파이배열명[start:]
넘파이배열명[:end]

-역순으로 표시
넘파이배열명[::-1]

In [ ]:
matrix_c = np.arange(0, 101, 10)
matrix_c

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
matrix_c[1:7:2]

array([10, 30, 50])

In [ ]:
matrix_c[:7]

array([ 0, 10, 20, 30, 40, 50, 60])

In [ ]:
matrix_c[5:]

array([ 50,  60,  70,  80,  90, 100])

In [ ]:
matrix_c[::2]

array([  0,  20,  40,  60,  80, 100])

In [ ]:
matrix_c[::-1]

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10,   0])

-넘파이 배열의 슬라이싱 1 : 2차원

넘파이배열명[start1:end1:step1, start2:end2:step2]

-역순으로 표시
넘파이배열명[::-1, ::]
넘파이배열명[::, ::-1]


In [ ]:
#5행 5열
matrix_d = np.arange(1, 26).reshape(5, 5)
matrix_d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
#1행만 출력
matrix_d[0, ::]

array([1, 2, 3, 4, 5])

In [ ]:
#1, 2행만 출력
matrix_d[0:2, ::]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
#1열만 출력
matrix_d[::, 0]

array([ 1,  6, 11, 16, 21])

In [ ]:
#3, 4열만 출력
matrix_d[::, 2:4:]

array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19],
       [23, 24]])

In [ ]:
#특정 행의 특정 열 슬라이싱
matrix_d[0:3, 0:2:]

array([[ 1,  2],
       [ 6,  7],
       [11, 12]])

In [ ]:
#홀수번째 행만 출력
matrix_d[::2, ::]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25]])

In [ ]:
#홀수번째 열만 출력
matrix_d[::, ::2]

array([[ 1,  3,  5],
       [ 6,  8, 10],
       [11, 13, 15],
       [16, 18, 20],
       [21, 23, 25]])

In [ ]:
#짝수번째 행 + 짝수번째 열
matrix_d[1::2, 1::2]

array([[ 7,  9],
       [17, 19]])

In [ ]:
#행 우선 역순
matrix_d[::, ::-1]

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11],
       [20, 19, 18, 17, 16],
       [25, 24, 23, 22, 21]])

In [ ]:
#열 우선 역순
matrix_d[::-1, ::]

array([[21, 22, 23, 24, 25],
       [16, 17, 18, 19, 20],
       [11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

전치 행렬

행과 열의 구조를 변경
넘파이행렬.T

In [ ]:
#3행 2열
matrix_e = np.arange(1,7).reshape(3,2 )
matrix_e

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#난수로 구성된 넘파이 배열 생성

In [ ]:
np.random?

In [ ]:
# 1~10 사이의 숫자중에서 10개 출력  
np.random.randint(1, 10, 10) 

array([9, 6, 6, 8, 1, 8, 8, 4, 9, 6])

In [ ]:
# 난수로 구성된 넘파이 배열 생성 

np.random.randint(start, end, n ) 정수로된 난수 생성  
np.random.randint(start, end, (i, j) ) i*j 구조로된 난수 2차원 넘파이 배열 생성

SyntaxError: invalid syntax (<ipython-input-130-6e8a38d5859c>, line 3)

In [ ]:
# 1~10 사이의 숫자중에서 임의로 뽑아서 2차원 배열 생성  
np.random.randint(1, 10, (5,2)) 

array([[5, 7],
       [8, 2],
       [3, 9],
       [8, 5],
       [2, 1]])

In [ ]:
#### 섞기 
```
np.random.shuffle(넘파이배열)
원본 배열에 바로 적용
```

In [ ]:
np.random.shuffle?

In [ ]:
matrix_e = np.arange(1,11)
matrix_e

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.random.shuffle(matrix_e)

In [ ]:
matrix_e

array([ 1,  5,  2,  8, 10,  3,  6,  9,  4,  7])

In [ ]:
# np.random.shuffle(matrix_e) print 문과 사용시 None 출력 
print(np.random.shuffle(matrix_e))

None


In [ ]:
print(matrix_e)

[ 6  9  2 10  8  3  4  1  7  5]


-퀴즈
1~46까지 구성된 숫자 중에서 6개를 뽑아서 로또 번호를 생성하여라

In [ ]:
matrix_l = np.arange(1, 47)
matrix_l

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46])

In [ ]:
np.random.shuffle(matrix_l)
matrix_l[:6]

array([ 4, 14, 39, 18, 26, 23])

-실수 난수

np.random.randn(n)
np.random.randn(i, j)

In [ ]:
matrix1 = np.random.randn(10)
matrix2 = np.random.randn(4, 4)

In [ ]:
matrix1

array([ 1.28664875, -0.5910631 ,  1.1995777 ,  0.64605278,  0.25623906,
       -1.50537265,  0.6622335 , -0.65579161,  1.23811457,  0.93793347])

In [ ]:
matrix2

array([[ 0.87048268, -0.20181076,  0.19380648, -0.32574899],
       [-0.92516731,  0.10367248, -0.51778147,  0.2413599 ],
       [-0.61832415,  0.08448459, -0.23763678, -1.85582794],
       [ 2.13827288,  0.97240417, -0.79009852, -1.92874286]])

-집계함수에서의 축

2차원에서 집계함수(sum, mean)
axis = 0 / 1 
np.sum(넘파이배열명, axis=0/1)
np.mean(넘파이배열명, axis=0/1)
np.sort(넘파이배열명, axis=0/1)

In [ ]:
#정수 난수로 구성된 2 x 5
m1 = np.random.randint(1, 50, (2, 5))
m1

array([[21, 20, 47,  9, 31],
       [36, 19, 27, 30, 16]])

In [ ]:
#세로방향으로 집계
np.sum(m1, axis=0)

array([57, 39, 74, 39, 47])

In [ ]:
#가로방향으로 집계
np.sum(m1, axis=1)

array([128, 128])

In [ ]:
#1행의 합계
np.sum(m1[0, :])

128

In [ ]:
np.sum(m1, axis=1)[0]

128

In [ ]:
np.max(m1, axis=1)

array([47, 36])

In [ ]:
np.max(m1, axis=0)

array([36, 20, 47, 30, 31])

np.sort() 테스트

In [ ]:
#정수 난수로 이루어진 4 x 3
m2 = np.random.randint(1, 50, (4, 3))
m2

array([[44, 38, 18],
       [15, 40, 36],
       [33, 14, 24],
       [44, 47, 44]])

In [ ]:
#세로 방향으로 값을 기준으로 한 오름차순 정렬
np.sort(m2, axis=0)

array([[15, 14, 18],
       [33, 38, 24],
       [44, 40, 36],
       [44, 47, 44]])

In [ ]:
# 원본은 그대로 유지 
# 원본을 변경하려면?
m2 = np.sort(m2, axis=0)

In [ ]:
# 내림차순으로 다시 정렬 
m2 = m2[::-1, ::]
m2

array([[44, 47, 44],
       [44, 40, 36],
       [33, 38, 24],
       [15, 14, 18]])

-인덱스 소팅

np.argsort(배열명, axis=0/1)
넘파이배열[np.argsort 배열] -> 오름차순한 결과

In [ ]:
x = np.array([3, 1, 2])
np.argsort(x)

array([1, 2, 0], dtype=int64)

In [ ]:
x[np.argsort(x)]

array([1, 2, 3])

In [ ]:
np.sort(x)

array([1, 2, 3])

-넘파이 배열의 추가와 삭제

추가)
np.insert(배열명, 위치인덱스, 값, axis=0/1)

2차원인 경우 axis를 설정하지 않는다면 1차원 배열로 변경된 후 값이 삽입됨
값은 리스트나 특정 숫자

In [ ]:
mm1 = np.arange(1, 11)
mm1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.insert(mm1, 0, 100)

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [ ]:
#끝에서 2번째에 데이터 삽입
np.insert(mm1, -1, 500)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9, 500,  10])

In [ ]:
mm1 = np.insert(mm1, 0, 100)
mm1

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [ ]:
# 마지막 위치에 값 삽입 
mm1 = np.insert(mm1, len(mm1), 500)
mm1

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 500])

In [ ]:
mm2 = np.arange(1, 10).reshape(3, 3)
mm2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#axis 값을 주지 않아서 1차원으로 변경 후 데이터 삽입
np.insert(mm2, 0, 100)

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [ ]:
#1행으로 [100, 100, 100]이 생성되서 삽입
np.insert(mm2, 0, 100, axis=0)

array([[100, 100, 100],
       [  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [ ]:
# 1열로 [100, 100, 100] 생성해서 삽입 
np.insert(mm2, 0, 100, axis=1)

array([[100,   1,   2,   3],
       [100,   4,   5,   6],
       [100,   7,   8,   9]])

In [ ]:
#리스트로 삽입 - 첫번째 컬럼으로 삽입
np.insert(mm2, 0, [100, 200, 300], axis=1)

array([[100,   1,   2,   3],
       [200,   4,   5,   6],
       [300,   7,   8,   9]])

In [ ]:
#리스트로 삽입 - 마지막 컬럼으로 삽입
np.insert(mm2, mm2.shape[1], [100, 200, 300], axis=1)

array([[  1,   2,   3, 100],
       [  4,   5,   6, 200],
       [  7,   8,   9, 300]])

In [ ]:
#리스트로 삽입 - 첫번째 행으로 삽입
np.insert(mm2, 0, [100, 200, 300], axis=0)

array([[100, 200, 300],
       [  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [ ]:
#리스트로 삽입 - 마지막 행으로 삽입
np.insert(mm2, mm2.shape[0], [100, 200, 300], axis=0)

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [100, 200, 300]])

-넘파이 배열의 추가와 삭제

삭제)
np.delete(배열명, 위치인덱스, axis=0/1)


In [ ]:
np.delete(mm2, 0, axis=1)

array([[2, 3],
       [5, 6],
       [8, 9]])

In [ ]:
np.delete(mm2, 0, axis=0)

array([[4, 5, 6],
       [7, 8, 9]])

-배열간 합치기

np.vstack((배열 1, 배열 2 ...)) : 세로로 합치기
np.hstack((배열 1, 배열 2 ...)) : 가로로 합치기

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a)
print(b)

[1 2 3]
[4 5 6]


In [ ]:
np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [ ]:
c = np.array([[1, 2, 3]]) #2차원
c, c.ndim, c.shape

(array([[1, 2, 3]]), 2, (1, 3))

In [ ]:
d = np.array([[4, 5, 6]])
d, d.ndim, d.shape

(array([[4, 5, 6]]), 2, (1, 3))

In [ ]:
np.concatenate( (c,d), axis=0 )

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate( (c,d), axis=1 )

array([[1, 2, 3, 4, 5, 6]])