In [1]:
import tensorflow as tf
import numpy as np

#### scalar data

In [ ]:
s1 = 10
s2 = 'abc'
s3 = 3.14

#### vector data

In [ ]:
v = [10, 20, 30]

#### matrix data

In [ ]:
# 2 X 3
m = [ [10 20, 30], [40, 50, 60] ] 

#### 3d tensor

In [ ]:
# 2 X 2 X 3
d3 =[ [[10 20, 30], [40, 50, 60]], [[10 20, 30], [40, 50, 60]] ]

#### 4d tensor

In [4]:
# 2 X 2 X 2 X 3
d4 = [ [ [[10 20, 30], [40, 50, 60]], [[10 20, 30], [40, 50, 60]] ],
[ [[10 20, 30], [40, 50, 60]], [[10 20, 30], [40, 50, 60]] ] ]

#### 텐서 데이터 노드 정의하는 방법

    1) constant : 읽기 전용
    2) variable : 읽기 + 쓰기

In [5]:
s1 = 10
c1 = tf.constant(s1)
c1 #텐서 객체

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [6]:
c1.numpy()

10

In [7]:
v1 = [10, 20, 30] #ndarray
t1 = tf.constant(v1)
t1

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 20, 30])>

In [9]:
type(t1)

tensorflow.python.framework.ops.EagerTensor

In [8]:
t1.numpy()

array([10, 20, 30])

In [10]:
m = [[10, 20, 30], [40, 50, 60]]
t2 = tf.constant(m)
t2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10, 20, 30],
       [40, 50, 60]])>

#### 연산 : element wise (요소별)

In [11]:
a = tf.constant(3)
b = tf.constant([1, 2, 3])

In [12]:
c = tf.multiply(a, b) #a X b
c

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 6, 9])>

In [13]:
c.numpy()

array([3, 6, 9])

In [14]:
d = tf.add(a, b) #a + b
d

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 5, 6])>

In [15]:
e = tf.add(c, b)
e

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4,  8, 12])>

#### broad casting

In [16]:
f = tf.constant([1, 2, 3])
g = tf.constant( [ [1, 2, 3], [4, 5, 6], [7, 8, 9] ] )
h = f + g #tf.add(f, g)

In [17]:
h.numpy()

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [18]:
i = tf.constant( [ [1], [2], [3] ] ) # 3 X 1
j = tf.constant( [ [1, 2, 3], [4, 5, 6], [7, 8, 9] ] )
k = i * j #tf.multify(i, j)

In [19]:
k.numpy()

array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21, 24, 27]])

In [26]:
# l = tf.constant([ [1], [2] ])
# m = tf.constant( [ [1, 2, 3], [4, 5, 6], [7, 8, 9] ] )
# n = l - m #tf.substract(l, m)
#shape error

#### 행렬곱 : 앞의 열, 뒤의 행 수가 같아야 가능

In [21]:
o = tf.constant( [ [1, 2], [3, 4] ] ) #2 X 2
p = tf.constant( [ [5, 6], [7, 8] ] ) #2 X 2
q = tf.multiply(o, p)
r = tf.matmul(o, p) #★★★★★ 중요

In [22]:
q.numpy()

array([[ 5, 12],
       [21, 32]])

In [23]:
r.numpy()

array([[19, 22],
       [43, 50]])

#### 많이 사용하는 operation

In [24]:
s = [1, 2, 3]
t = tf.square(s) #s**2
t

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 9])>

In [25]:
u = tf.reduce_mean(s) #(누적)평균
u

<tf.Tensor: shape=(), dtype=int32, numpy=2>

#### Variable

In [28]:
v = tf.Variable(10)
v
#값이 고정되지 않음

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>

In [ ]:
#v = 20 이런 식으로 변경 X

In [ ]:
#v.assign(3) #3으로 변경
#v.assign_add(3) #기존값 + 3
v.assign_sub(3) #기존값 - 3