In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
import numpy as np

In [3]:
x_data = np.array( [[0,0],[0,1],[1,0],[1,1]] )
y_data = np.array( [[0],[1],[1],[0] ] )

In [4]:
model_logi = LogisticRegression(max_iter = 1000, verbose=1)
model_logi.fit(x_data, y_data )

C:\Users\TFG5076XG\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


LogisticRegression(max_iter=1000, verbose=1)

In [5]:
model_logi.coef_

array([[0., 0.]])

In [6]:
model_logi.intercept_

array([0.])

In [7]:
model_logi.predict(x_data)

array([0, 0, 0, 0])

In [9]:
model_logi.score(x_data, y_data)

0.5

#### 딥러닝

In [10]:
model_mlp = MLPClassifier(hidden_layer_sizes=(100,), max_iter=1000, verbose=True)
model_mlp.fit(x_data, y_data)

C:\Users\TFG5076XG\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


Iteration 1, loss = 0.69912366
Iteration 2, loss = 0.69748200
Iteration 3, loss = 0.69586784
Iteration 4, loss = 0.69441939
Iteration 5, loss = 0.69307968
Iteration 6, loss = 0.69180842
Iteration 7, loss = 0.69063688
Iteration 8, loss = 0.68956755
Iteration 9, loss = 0.68851915
Iteration 10, loss = 0.68752689
Iteration 11, loss = 0.68658168
Iteration 12, loss = 0.68559858
Iteration 13, loss = 0.68462050
Iteration 14, loss = 0.68368460
Iteration 15, loss = 0.68274096
Iteration 16, loss = 0.68179570
Iteration 17, loss = 0.68084706
Iteration 18, loss = 0.67989924
Iteration 19, loss = 0.67896627
Iteration 20, loss = 0.67803492
Iteration 21, loss = 0.67710567
Iteration 22, loss = 0.67618721
Iteration 23, loss = 0.67531073
Iteration 24, loss = 0.67444908
Iteration 25, loss = 0.67358982
Iteration 26, loss = 0.67272792
Iteration 27, loss = 0.67185568
Iteration 28, loss = 0.67098429
Iteration 29, loss = 0.67010297
Iteration 30, loss = 0.66921527
Iteration 31, loss = 0.66833342
Iteration 32, los

Iteration 611, loss = 0.06867677
Iteration 612, loss = 0.06835052
Iteration 613, loss = 0.06801845
Iteration 614, loss = 0.06770275
Iteration 615, loss = 0.06738250
Iteration 616, loss = 0.06706015
Iteration 617, loss = 0.06674028
Iteration 618, loss = 0.06641555
Iteration 619, loss = 0.06611814
Iteration 620, loss = 0.06582082
Iteration 621, loss = 0.06552521
Iteration 622, loss = 0.06523375
Iteration 623, loss = 0.06493938
Iteration 624, loss = 0.06464589
Iteration 625, loss = 0.06434657
Iteration 626, loss = 0.06406521
Iteration 627, loss = 0.06378279
Iteration 628, loss = 0.06348911
Iteration 629, loss = 0.06319699
Iteration 630, loss = 0.06292054
Iteration 631, loss = 0.06263776
Iteration 632, loss = 0.06235160
Iteration 633, loss = 0.06206323
Iteration 634, loss = 0.06178761
Iteration 635, loss = 0.06151365
Iteration 636, loss = 0.06123347
Iteration 637, loss = 0.06095513
Iteration 638, loss = 0.06067771
Iteration 639, loss = 0.06040608
Iteration 640, loss = 0.06013369
Iteration 

MLPClassifier(max_iter=1000, verbose=True)

In [11]:
model_mlp.predict(x_data) # 4x2  2x100  4x100  100x1  = 4x1

array([0, 1, 1, 0])

In [19]:
model_mlp.score(x_data, y_data)

1.0

In [13]:
len(model_mlp.coefs_)

2

In [15]:
model_mlp.coefs_[0].shape

(2, 100)

In [16]:
model_mlp.coefs_[1].shape

(100, 1)

In [17]:
model_mlp.intercepts_[0].shape

(100,)

In [18]:
model_mlp.intercepts_[1].shape

(1,)

In [20]:
model_mlp1 = MLPClassifier(hidden_layer_sizes=(100,50), max_iter=1000, verbose=True)
model_mlp1.fit(x_data, y_data)      #2(특성데이터)  1(라벨)
                                    #2x100, 100x50, 50x1
                        #4x2  2x100 = 4x100  100x50  = 4x50  50x1  = 4x1

Iteration 1, loss = 0.71493195
Iteration 2, loss = 0.70746054
Iteration 3, loss = 0.70091816
Iteration 4, loss = 0.69463393
Iteration 5, loss = 0.68869741
Iteration 6, loss = 0.68331059
Iteration 7, loss = 0.67845085
Iteration 8, loss = 0.67373856
Iteration 9, loss = 0.66938532
Iteration 10, loss = 0.66557643
Iteration 11, loss = 0.66198353
Iteration 12, loss = 0.65876174
Iteration 13, loss = 0.65567094
Iteration 14, loss = 0.65252554
Iteration 15, loss = 0.64935641
Iteration 16, loss = 0.64618697
Iteration 17, loss = 0.64287448
Iteration 18, loss = 0.63960276
Iteration 19, loss = 0.63626499
Iteration 20, loss = 0.63286560
Iteration 21, loss = 0.62955639
Iteration 22, loss = 0.62620694
Iteration 23, loss = 0.62324069
Iteration 24, loss = 0.62008923
Iteration 25, loss = 0.61675746
Iteration 26, loss = 0.61327531
Iteration 27, loss = 0.60978484
Iteration 28, loss = 0.60620663
Iteration 29, loss = 0.60255114
Iteration 30, loss = 0.59894775
Iteration 31, loss = 0.59521357
Iteration 32, los

C:\Users\TFG5076XG\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


MLPClassifier(hidden_layer_sizes=(100, 50), max_iter=1000, verbose=True)

In [21]:
len(model_mlp1.coefs_)

3

In [22]:
model_mlp1.coefs_[0].shape

(2, 100)

In [23]:
model_mlp1.coefs_[1].shape

(100, 50)

In [24]:
model_mlp1.coefs_[2].shape

(50, 1)

In [25]:
model_mlp2 = MLPClassifier(hidden_layer_sizes=(64,32,16), max_iter=1000, verbose=True)
model_mlp2.fit(x_data, y_data)          #2(특성데이터)  1(라벨)
                                    #2x64, 64x32, 32x16, 16x1
                        #4x2  2x64 = 4x64  64x32  = 4x32  32x16  = 4x16  16x1  = 4x1

Iteration 1, loss = 0.81543143
Iteration 2, loss = 0.80307655
Iteration 3, loss = 0.79097363
Iteration 4, loss = 0.77957803
Iteration 5, loss = 0.76863069
Iteration 6, loss = 0.75839369
Iteration 7, loss = 0.74864725
Iteration 8, loss = 0.73932604
Iteration 9, loss = 0.73022102
Iteration 10, loss = 0.72156371
Iteration 11, loss = 0.71379601
Iteration 12, loss = 0.70644006
Iteration 13, loss = 0.69950917
Iteration 14, loss = 0.69311268
Iteration 15, loss = 0.68894581
Iteration 16, loss = 0.68498424
Iteration 17, loss = 0.68152568
Iteration 18, loss = 0.67907090
Iteration 19, loss = 0.67628318
Iteration 20, loss = 0.67310976
Iteration 21, loss = 0.66982360
Iteration 22, loss = 0.66643857
Iteration 23, loss = 0.66288045
Iteration 24, loss = 0.65943643
Iteration 25, loss = 0.65574235
Iteration 26, loss = 0.65236742
Iteration 27, loss = 0.64984736
Iteration 28, loss = 0.64719248
Iteration 29, loss = 0.64428514
Iteration 30, loss = 0.64103385
Iteration 31, loss = 0.63766203
Iteration 32, los

C:\Users\TFG5076XG\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


MLPClassifier(hidden_layer_sizes=(64, 32, 16), max_iter=1000, verbose=True)

In [26]:
len(model_mlp2.coefs_)

4

In [27]:
model_mlp2.coefs_[0].shape

(2, 64)

In [28]:
model_mlp2.coefs_[1].shape

(64, 32)

In [29]:
model_mlp2.coefs_[2].shape

(32, 16)

In [30]:
model_mlp2.coefs_[3].shape

(16, 1)