In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
plt.style.use("ggplot")

from tensorflow.keras.optimizers import Adam
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [3]:
df = pd.read_csv('data/softmax.txt', sep=' ', header=None)
df
#0, 1 특성데이터, 2, 3, 4 라벨

0  1  2  3  4
0  2  1  0  0  1
1  3  2  0  0  1
2  3  4  0  0  1
3  5  5  0  1  0
4  7  5  0  1  0
5  2  5  0  1  0
6  6  6  1  0  0
7  7  7  1  0  0

In [4]:
x_data = df.iloc[:, 0:2]
y_data = df.iloc[:, 2:]

In [5]:
x_data

0  1
0  2  1
1  3  2
2  3  4
3  5  5
4  7  5
5  2  5
6  6  6
7  7  7

In [6]:
y_datao

2  3  4
0  0  0  1
1  0  0  1
2  0  0  1
3  0  1  0
4  0  1  0
5  0  1  0
6  1  0  0
7  1  0  0

In [7]:
x = tf.constant(x_data, tf.float32)
y = tf.constant(y_data, tf.float32)

In [8]:
initX = tf.initializers.GlorotUniform()
w = tf.Variable( initX( shape = [2, 3]) ) #특성데이터 갯수, 라벨 갯수
b = tf.Variable( initX( shape = [3]) ) #라벨 갯수

In [11]:
def compute_loss():
    z = tf.matmul(x, w) + b
#     hx = tf.nn.softmax(z)
    cost_i = tf.nn.softmax_cross_entropy_with_logits(labels = y, logits = z) #시그마 이전까지
    cost = tf.reduce_mean(cost_i) #전체 수식 계산
    return cost

In [12]:
optimizer = Adam(0.1)
for i in range(1000):
    optimizer.minimize(compute_loss, var_list = [w, b])
    print( i, 'cost : ', compute_loss().numpy() )

0 cost :  2.3831878
1 cost :  2.2701554
2 cost :  2.0239048
3 cost :  1.7309122
4 cost :  1.5187886
5 cost :  1.4398825
6 cost :  1.4695241
7 cost :  1.5883065
8 cost :  1.673562
9 cost :  1.6354332
10 cost :  1.5131211
11 cost :  1.3914884
12 cost :  1.3284624
13 cost :  1.3204769
14 cost :  1.336633
15 cost :  1.3556226
16 cost :  1.3689878
17 cost :  1.3722364
18 cost :  1.360514
19 cost :  1.3318257
20 cost :  1.2904203
21 cost :  1.2451706
22 cost :  1.2057352
23 cost :  1.1805124
24 cost :  1.174804
25 cost :  1.1848456
26 cost :  1.1944056
27 cost :  1.1869944
28 cost :  1.1620312
29 cost :  1.1331525
30 cost :  1.1132457
31 cost :  1.1055264
32 cost :  1.1061883
33 cost :  1.1091607
34 cost :  1.1085758
35 cost :  1.1012031
36 cost :  1.088321
37 cost :  1.074739
38 cost :  1.0655179
39 cost :  1.062922
40 cost :  1.0651039
41 cost :  1.0671601
42 cost :  1.0648713
43 cost :  1.058333
44 cost :  1.0513505
45 cost :  1.0474327
46 cost :  1.0471065
47 cost :  1.0485135
48 cost : 

380 cost :  1.0376614
381 cost :  1.0376616
382 cost :  1.0376613
383 cost :  1.0376613
384 cost :  1.0376614
385 cost :  1.0376616
386 cost :  1.0376616
387 cost :  1.0376614
388 cost :  1.0376613
389 cost :  1.0376613
390 cost :  1.0376613
391 cost :  1.0376616
392 cost :  1.0376613
393 cost :  1.0376613
394 cost :  1.0376614
395 cost :  1.0376614
396 cost :  1.0376614
397 cost :  1.0376614
398 cost :  1.0376614
399 cost :  1.0376613
400 cost :  1.0376614
401 cost :  1.0376614
402 cost :  1.0376614
403 cost :  1.0376613
404 cost :  1.0376613
405 cost :  1.0376613
406 cost :  1.0376613
407 cost :  1.0376613
408 cost :  1.0376613
409 cost :  1.0376613
410 cost :  1.0376616
411 cost :  1.0376613
412 cost :  1.0376613
413 cost :  1.0376613
414 cost :  1.0376616
415 cost :  1.0376614
416 cost :  1.0376613
417 cost :  1.0376614
418 cost :  1.0376614
419 cost :  1.0376613
420 cost :  1.0376614
421 cost :  1.0376613
422 cost :  1.0376613
423 cost :  1.0376613
424 cost :  1.0376616
425 cost :

754 cost :  1.0376614
755 cost :  1.0376614
756 cost :  1.0376613
757 cost :  1.0376613
758 cost :  1.0376613
759 cost :  1.0376613
760 cost :  1.0376614
761 cost :  1.0376612
762 cost :  1.0376612
763 cost :  1.0376613
764 cost :  1.0376613
765 cost :  1.0376613
766 cost :  1.0376613
767 cost :  1.0376613
768 cost :  1.0376613
769 cost :  1.0376616
770 cost :  1.0376613
771 cost :  1.0376614
772 cost :  1.0376611
773 cost :  1.0376614
774 cost :  1.0376616
775 cost :  1.0376613
776 cost :  1.0376616
777 cost :  1.0376614
778 cost :  1.0376613
779 cost :  1.0376612
780 cost :  1.0376614
781 cost :  1.0376616
782 cost :  1.0376616
783 cost :  1.0376614
784 cost :  1.0376613
785 cost :  1.0376614
786 cost :  1.0376613
787 cost :  1.0376614
788 cost :  1.0376616
789 cost :  1.0376616
790 cost :  1.0376612
791 cost :  1.0376613
792 cost :  1.0376613
793 cost :  1.0376613
794 cost :  1.0376616
795 cost :  1.0376616
796 cost :  1.0376614
797 cost :  1.0376614
798 cost :  1.0376613
799 cost :

In [13]:
w.numpy()
#w1x1, w2x1, w3x1
#w1x2, w2x2, w3x2

array([[0.26836795, 0.12529162, 0.5480252 ],
       [1.1220857 , 1.2844005 , 0.7136625 ]], dtype=float32)

In [20]:
def hxfn(x_data):
    xd = tf.constant(x_data, tf.float32)
    z = tf.matmul(xd, w) + b
    hx = tf.nn.softmax(z)
    return hx.numpy()
#     return hx.numpy().argmax( axis = 1)
#     return z.numpy(), hx.numpy() 

In [19]:
hxfn( [[5, 6]] )

array([1], dtype=int64)

In [22]:
arr = hxfn( [[1, 1], [5, 6]] )
arr.argmax(axis = 1)

array([1, 1], dtype=int64)

In [17]:
arr = np.array( [[1, 2, 3], [4, 5, 6]] )
arr.argmax( axis=1 ) #행 단위로 가장 큰 값의 인덱스

array([2, 2], dtype=int64)

In [24]:
x_data.shape

(8, 2)

In [25]:
pred = hxfn(x_data).argmax(axis = 1)
pred

array([2, 2, 1, 1, 0, 1, 1, 1], dtype=int64)

In [28]:
r = y_data.values.argmax(axis=1)
r

array([2, 2, 2, 1, 1, 1, 0, 0], dtype=int64)

In [29]:
(pred==r).mean()

0.5