In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tensorflow.keras.optimizers import Adam

In [2]:
x_data = np.array( [[0,0],[0,1],[1,0],[1,1]] )
y_data = np.array( [[0],[1],[1],[0] ] )

In [3]:
x = tf.constant(x_data, tf.float32)
y = tf.constant(y_data, tf.float32)

In [4]:
# initX = tf.initializers.GlorotUniform() #32의 배수로?

# w1 = tf.Variable( initX( shape = [2, 100] ) )
# b1 = tf.Variable( initX( shape = [100] ) )

# w2 = tf.Variable( initX( shape = [100, 1] ) )
# b2 = tf.Variable( initX( shape = [1] ) )
# 2행 1열짜리 3개로 해도 됨

In [5]:
initX = tf.initializers.GlorotUniform() #32의 배수로?

w1 = tf.Variable( initX( shape = [2, 64] ) )
b1 = tf.Variable( initX( shape = [64] ) )

w2 = tf.Variable( initX( shape = [64, 32] ) )
b2 = tf.Variable( initX( shape = [32] ) )

w3 = tf.Variable( initX( shape = [32, 1] ) )
b3 = tf.Variable( initX( shape = [1] ) )

In [6]:
# def compute_loss():
#     z1 = tf.matmul(x, w1) + b1
#     hx1 = tf.nn.sigmoid(z1) #4행 2열 됨
#     z = tf.matmul(hx1, w2) + b2 #최종 z값
    
#     cost_i = tf.nn.sigmoid_cross_entropy_with_logits( logits = z, labels = y )
#     cost = tf.reduce_mean(cost_i)
#     return cost

In [7]:
def compute_loss():
    z1 = tf.matmul(x, w1) + b1
    hx1 = tf.nn.sigmoid(z1) #4행 2열 됨
    
    z2 = tf.matmul(hx1, w2) + b2 #최종 z값
    hx2 = tf.nn.sigmoid(z2)
    
    z = tf.matmul(hx2, w3) + b3
#     hx = tf.nn.sigmoid(z)
    
    cost_i = tf.nn.sigmoid_cross_entropy_with_logits( logits = z, labels = y )
    cost = tf.reduce_mean(cost_i)
    return cost

In [8]:
optimizer = Adam( learning_rate = 0.1)
for i in range(1000):
#     optimizer.minimize (compute_loss, var_list = [w1, w2, b1, b2])
    optimizer.minimize (compute_loss, var_list = [w1, w2, w3, b1, b2, b3])
    print(i, compute_loss().numpy() )

0 2.4424212
1 1.7291317
2 0.92939794
3 0.7047827
4 0.89579755
5 1.0197282
6 1.0260148
7 0.95437515
8 0.84717286
9 0.74862754
10 0.69529647
11 0.6989516
12 0.73893845
13 0.7789263
14 0.7942091
15 0.7823312
16 0.7522315
17 0.7173077
18 0.6911949
19 0.6816361
20 0.68737835
21 0.699895
22 0.70992136
23 0.71174955
24 0.70407724
25 0.68924475
26 0.67168945
27 0.65596527
28 0.6447478
29 0.6376745
30 0.63188046
31 0.624187
32 0.61357975
33 0.60202914
34 0.59257734
35 0.58593476
36 0.57923746
37 0.5693091
38 0.5564761
39 0.54388225
40 0.5341296
41 0.52740926
42 0.5220745
43 0.5164424
44 0.51008195
45 0.503644
46 0.49791056
47 0.4931683
48 0.48926327
49 0.48595345
50 0.4831
51 0.4805269
52 0.47781795
53 0.4746155
54 0.4711058
55 0.46766225
56 0.4641518
57 0.46001044
58 0.45474672
59 0.44866866
60 0.44290936
61 0.43571204
62 0.4246366
63 0.4129869
64 0.40036157
65 0.38439876
66 0.36662638
67 0.3495195
68 0.3311475
69 0.31197408
70 0.29420817
71 0.27682504
72 0.25968802
73 0.24329409
74 0.22790144

533 0.0014257072
534 0.0014214498
535 0.0014172128
536 0.001412997
537 0.0014088004
538 0.0014046242
539 0.0014004667
540 0.00139633
541 0.0013922127
542 0.0013881146
543 0.0013840361
544 0.0013799763
545 0.001375935
546 0.0013719139
547 0.0013679108
548 0.0013639263
549 0.0013599606
550 0.0013560136
551 0.0013520846
552 0.0013481736
553 0.0013442809
554 0.001340406
555 0.0013365495
556 0.0013327098
557 0.0013288887
558 0.0013250851
559 0.0013212973
560 0.0013175278
561 0.0013137765
562 0.0013100405
563 0.0013063219
564 0.001302621
565 0.0012989356
566 0.0012952685
567 0.0012916154
568 0.0012879807
569 0.0012843616
570 0.0012807599
571 0.0012771724
572 0.0012736018
573 0.0012700479
574 0.0012665079
575 0.0012629863
576 0.0012594785
577 0.0012559864
578 0.0012525098
579 0.00124905
580 0.0012456025
581 0.0012421724
582 0.001238757
583 0.0012353563
584 0.0012319698
585 0.0012285988
586 0.001225242
587 0.0012219006
588 0.0012185735
589 0.0012152599
590 0.001211961
591 0.0012086771
592 0.00

In [15]:
def hxfn( x_data ):
    xd = tf.constant( x_data, tf.float32 )
    
    z1 = tf.matmul( xd, w1 ) + b1
    hx1 = tf.nn.sigmoid( z1 )
    
    z2 = tf.matmul( hx1, w2 ) + b2
    hx2 = tf.nn.sigmoid( z2 )

    z3 = tf.matmul( hx2, w3 ) + b3
    hx = tf.nn.sigmoid( z3 )
    
    return (hx.numpy() > 0.5) + 0

In [16]:
hxfn(x_data) #4x2  2x64 = 4x64  64x32  4x32  32x1 = 4x1

array([[0],
       [1],
       [1],
       [0]])

In [17]:
w1.numpy()

array([[-1.1339195 , -1.2988394 , -2.6046157 , -3.5225666 , -2.3672316 ,
        -3.7166243 , -2.4726336 , -3.871417  , -0.22701044, -4.163155  ,
        -2.3648326 , -4.3017087 , -2.4002256 , -3.7943032 , -3.7450838 ,
        -3.0134113 , -0.19409263, -3.065016  , -1.8603411 , -3.1398897 ,
        -3.6966126 ,  1.0136557 , -4.2854915 , -3.17244   , -1.7966266 ,
        -3.9313369 , -3.8811529 , -2.0574644 , -3.0614867 , -2.962673  ,
        -3.5649385 , -5.065179  , -3.552418  , -5.161907  , -0.09892733,
        -2.7173612 , -2.8945045 ,  0.87641716, -3.5519717 , -3.359605  ,
        -4.0240664 , -3.599131  , -3.7332728 , -5.379677  , -2.229041  ,
        -4.9518323 , -2.781311  , -2.5405278 , -2.9542017 , -3.135436  ,
        -2.8153052 , -2.972447  , -2.7645564 , -3.048752  , -3.2584214 ,
        -2.356032  , -1.930645  , -6.0194654 , -2.763946  , -3.839274  ,
        -2.0821242 , -3.5256999 , -6.1846457 , -1.8702512 ],
       [-5.620773  , -4.6643114 , -2.456184  , -3.3911338 , -2.

In [18]:
w2.numpy()

array([[-0.7654276 ,  0.90582496, -0.62662834, ..., -1.4152889 ,
        -1.4971215 ,  2.2396653 ],
       [-0.8404759 ,  0.6075955 , -0.82353204, ..., -0.990681  ,
        -1.0673254 ,  0.6736107 ],
       [-0.7637511 ,  0.9340655 , -1.0397518 , ..., -0.92628735,
        -0.89851373, -0.57787895],
       ...,
       [-0.44133094,  0.90310913, -0.49251038, ..., -0.6427752 ,
        -1.0127195 , -0.8321777 ],
       [-0.81060654,  0.63259506, -0.7089723 , ..., -0.9514791 ,
        -1.1620094 ,  1.8616955 ],
       [-0.41464853,  0.9097093 , -0.73228765, ..., -0.55943507,
        -0.7766417 , -0.41933537]], dtype=float32)