In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [2]:
x_data = np.array( [[0,0],[0,1],[1,0],[1,1]] )
y_data = np.array( [[0],[1],[1],[0] ] )

In [3]:
dense1 = Dense(units = 100, input_dim = 2, activation = 'sigmoid') #w : 2 X 100, b : 100   (b = label)
dense2 = Dense(units = 1, input_dim = 100, activation = 'sigmoid') #w : 100 X 1, b : 1
#dense1의 input_dim 과 dense2의 units 맞추기
model = Sequential([dense1, dense2])
model.compile(loss='binary_crossentropy', optimizer=Adam(0.1), metrics=['acc']) #로그함수 적용/ 정확도 출력
h = model.fit(x_data, y_data, epochs = 1000)

Epoch 1/1000
1/1 [==============================] - 0s 262ms/step - loss: 0.7374 - acc: 0.5000
Epoch 2/1000
1/1 [==============================] - 0s 2ms/step - loss: 2.5141 - acc: 0.5000
Epoch 3/1000
1/1 [==============================] - 0s 996us/step - loss: 1.1779 - acc: 0.5000
Epoch 4/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.9624 - acc: 0.5000
Epoch 5/1000
1/1 [==============================] - 0s 970us/step - loss: 1.4441 - acc: 0.5000
Epoch 6/1000
1/1 [==============================] - 0s 998us/step - loss: 1.2419 - acc: 0.5000
Epoch 7/1000
1/1 [==============================] - 0s 998us/step - loss: 0.8174 - acc: 0.5000
Epoch 8/1000
1/1 [==============================] - 0s 998us/step - loss: 0.7286 - acc: 0.5000
Epoch 9/1000
1/1 [==============================] - 0s 998us/step - loss: 0.9403 - acc: 0.5000
Epoch 10/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.0342 - acc: 0.5000
Epoch 11/1000
1/1 [==============================] - 0s

1/1 [==============================] - 0s 2ms/step - loss: 0.2595 - acc: 0.7500
Epoch 88/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2515 - acc: 1.0000
Epoch 89/1000
1/1 [==============================] - 0s 998us/step - loss: 0.2436 - acc: 1.0000
Epoch 90/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2357 - acc: 1.0000
Epoch 91/1000
1/1 [==============================] - 0s 997us/step - loss: 0.2278 - acc: 1.0000
Epoch 92/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2200 - acc: 1.0000
Epoch 93/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2122 - acc: 1.0000
Epoch 94/1000
1/1 [==============================] - 0s 998us/step - loss: 0.2045 - acc: 1.0000
Epoch 95/1000
1/1 [==============================] - 0s 997us/step - loss: 0.1969 - acc: 1.0000
Epoch 96/1000
1/1 [==============================] - 0s 992us/step - loss: 0.1895 - acc: 1.0000
Epoch 97/1000
1/1 [==============================] - 0s 997us/st

1/1 [==============================] - 0s 2ms/step - loss: 0.0167 - acc: 1.0000
Epoch 173/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0163 - acc: 1.0000
Epoch 174/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0159 - acc: 1.0000
Epoch 175/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0155 - acc: 1.0000
Epoch 176/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0152 - acc: 1.0000
Epoch 177/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0148 - acc: 1.0000
Epoch 178/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0145 - acc: 1.0000
Epoch 179/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0142 - acc: 1.0000
Epoch 180/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0139 - acc: 1.0000
Epoch 181/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0136 - acc: 1.0000
Epoch 182/1000
1/1 [==============================] - 0

1/1 [==============================] - 0s 2ms/step - loss: 0.0050 - acc: 1.0000
Epoch 258/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0050 - acc: 1.0000
Epoch 259/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0049 - acc: 1.0000
Epoch 260/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0049 - acc: 1.0000
Epoch 261/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0048 - acc: 1.0000
Epoch 262/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0048 - acc: 1.0000
Epoch 263/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0047 - acc: 1.0000
Epoch 264/1000
1/1 [==============================] - 0s 988us/step - loss: 0.0047 - acc: 1.0000
Epoch 265/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0047 - acc: 1.0000
Epoch 266/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0046 - acc: 1.0000
Epoch 267/1000
1/1 [==============================] - 0

1/1 [==============================] - 0s 997us/step - loss: 0.0027 - acc: 1.0000
Epoch 343/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0027 - acc: 1.0000
Epoch 344/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0027 - acc: 1.0000
Epoch 345/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0027 - acc: 1.0000
Epoch 346/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0027 - acc: 1.0000
Epoch 347/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0026 - acc: 1.0000
Epoch 348/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0026 - acc: 1.0000
Epoch 349/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0026 - acc: 1.0000
Epoch 350/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0026 - acc: 1.0000
Epoch 351/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0026 - acc: 1.0000
Epoch 352/1000
1/1 [==============================]

1/1 [==============================] - 0s 998us/step - loss: 0.0018 - acc: 1.0000
Epoch 428/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0017 - acc: 1.0000
Epoch 429/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0017 - acc: 1.0000
Epoch 430/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0017 - acc: 1.0000
Epoch 431/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0017 - acc: 1.0000
Epoch 432/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0017 - acc: 1.0000
Epoch 433/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0017 - acc: 1.0000
Epoch 434/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.0017 - acc: 1.0000
Epoch 435/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0017 - acc: 1.0000
Epoch 436/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0017 - acc: 1.0000
Epoch 437/1000
1/1 [==============================] -

1/1 [==============================] - 0s 2ms/step - loss: 0.0012 - acc: 1.0000
Epoch 513/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0012 - acc: 1.0000
Epoch 514/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0012 - acc: 1.0000
Epoch 515/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0012 - acc: 1.0000
Epoch 516/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0012 - acc: 1.0000
Epoch 517/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0012 - acc: 1.0000
Epoch 518/1000
1/1 [==============================] - 0s 991us/step - loss: 0.0012 - acc: 1.0000
Epoch 519/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0012 - acc: 1.0000
Epoch 520/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0012 - acc: 1.0000
Epoch 521/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0012 - acc: 1.0000
Epoch 522/1000
1/1 [==============================] -

1/1 [==============================] - 0s 2ms/step - loss: 9.0411e-04 - acc: 1.0000
Epoch 597/1000
1/1 [==============================] - 0s 2ms/step - loss: 9.0094e-04 - acc: 1.0000
Epoch 598/1000
1/1 [==============================] - 0s 997us/step - loss: 8.9778e-04 - acc: 1.0000
Epoch 599/1000
1/1 [==============================] - 0s 999us/step - loss: 8.9464e-04 - acc: 1.0000
Epoch 600/1000
1/1 [==============================] - 0s 2ms/step - loss: 8.9151e-04 - acc: 1.0000
Epoch 601/1000
1/1 [==============================] - 0s 997us/step - loss: 8.8840e-04 - acc: 1.0000
Epoch 602/1000
1/1 [==============================] - 0s 1ms/step - loss: 8.8531e-04 - acc: 1.0000
Epoch 603/1000
1/1 [==============================] - 0s 2ms/step - loss: 8.8222e-04 - acc: 1.0000
Epoch 604/1000
1/1 [==============================] - 0s 997us/step - loss: 8.7916e-04 - acc: 1.0000
Epoch 605/1000
1/1 [==============================] - 0s 2ms/step - loss: 8.7610e-04 - acc: 1.0000
Epoch 606/1000
1/

1/1 [==============================] - 0s 1ms/step - loss: 6.9046e-04 - acc: 1.0000
Epoch 678/1000
1/1 [==============================] - 0s 997us/step - loss: 6.8831e-04 - acc: 1.0000
Epoch 679/1000
1/1 [==============================] - 0s 2ms/step - loss: 6.8616e-04 - acc: 1.0000
Epoch 680/1000
1/1 [==============================] - 0s 997us/step - loss: 6.8403e-04 - acc: 1.0000
Epoch 681/1000
1/1 [==============================] - 0s 998us/step - loss: 6.8190e-04 - acc: 1.0000
Epoch 682/1000
1/1 [==============================] - 0s 2ms/step - loss: 6.7979e-04 - acc: 1.0000
Epoch 683/1000
1/1 [==============================] - 0s 2ms/step - loss: 6.7769e-04 - acc: 1.0000
Epoch 684/1000
1/1 [==============================] - 0s 2ms/step - loss: 6.7560e-04 - acc: 1.0000
Epoch 685/1000
1/1 [==============================] - 0s 997us/step - loss: 6.7351e-04 - acc: 1.0000
Epoch 686/1000
1/1 [==============================] - 0s 997us/step - loss: 6.7144e-04 - acc: 1.0000
Epoch 687/1000


1/1 [==============================] - 0s 998us/step - loss: 5.4489e-04 - acc: 1.0000
Epoch 759/1000
1/1 [==============================] - 0s 2ms/step - loss: 5.4340e-04 - acc: 1.0000
Epoch 760/1000
1/1 [==============================] - 0s 998us/step - loss: 5.4192e-04 - acc: 1.0000
Epoch 761/1000
1/1 [==============================] - 0s 2ms/step - loss: 5.4045e-04 - acc: 1.0000
Epoch 762/1000
1/1 [==============================] - 0s 997us/step - loss: 5.3899e-04 - acc: 1.0000
Epoch 763/1000
1/1 [==============================] - 0s 2ms/step - loss: 5.3753e-04 - acc: 1.0000
Epoch 764/1000
1/1 [==============================] - 0s 997us/step - loss: 5.3608e-04 - acc: 1.0000
Epoch 765/1000
1/1 [==============================] - 0s 998us/step - loss: 5.3463e-04 - acc: 1.0000
Epoch 766/1000
1/1 [==============================] - 0s 2ms/step - loss: 5.3319e-04 - acc: 1.0000
Epoch 767/1000
1/1 [==============================] - 0s 997us/step - loss: 5.3176e-04 - acc: 1.0000
Epoch 768/100

1/1 [==============================] - 0s 997us/step - loss: 4.4160e-04 - acc: 1.0000
Epoch 841/1000
1/1 [==============================] - 0s 2ms/step - loss: 4.4054e-04 - acc: 1.0000
Epoch 842/1000
1/1 [==============================] - 0s 998us/step - loss: 4.3948e-04 - acc: 1.0000
Epoch 843/1000
1/1 [==============================] - 0s 996us/step - loss: 4.3843e-04 - acc: 1.0000
Epoch 844/1000
1/1 [==============================] - 0s 2ms/step - loss: 4.3738e-04 - acc: 1.0000
Epoch 845/1000
1/1 [==============================] - 0s 998us/step - loss: 4.3633e-04 - acc: 1.0000
Epoch 846/1000
1/1 [==============================] - 0s 2ms/step - loss: 4.3529e-04 - acc: 1.0000
Epoch 847/1000
1/1 [==============================] - 0s 997us/step - loss: 4.3425e-04 - acc: 1.0000
Epoch 848/1000
1/1 [==============================] - 0s 1ms/step - loss: 4.3321e-04 - acc: 1.0000
Epoch 849/1000
1/1 [==============================] - 0s 997us/step - loss: 4.3218e-04 - acc: 1.0000
Epoch 850/100

1/1 [==============================] - 0s 2ms/step - loss: 3.6697e-04 - acc: 1.0000
Epoch 922/1000
1/1 [==============================] - 0s 997us/step - loss: 3.6617e-04 - acc: 1.0000
Epoch 923/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.6538e-04 - acc: 1.0000
Epoch 924/1000
1/1 [==============================] - 0s 981us/step - loss: 3.6459e-04 - acc: 1.0000
Epoch 925/1000
1/1 [==============================] - 0s 997us/step - loss: 3.6380e-04 - acc: 1.0000
Epoch 926/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.6302e-04 - acc: 1.0000
Epoch 927/1000
1/1 [==============================] - 0s 997us/step - loss: 3.6223e-04 - acc: 1.0000
Epoch 928/1000
1/1 [==============================] - 0s 997us/step - loss: 3.6145e-04 - acc: 1.0000
Epoch 929/1000
1/1 [==============================] - 0s 997us/step - loss: 3.6068e-04 - acc: 1.0000
Epoch 930/1000
1/1 [==============================] - 0s 997us/step - loss: 3.5990e-04 - acc: 1.0000
Epoch 931/1

In [4]:
(model.predict(x_data) > 0.5) + 0

array([[0],
       [1],
       [1],
       [0]])

In [7]:
w, b = dense1.get_weights()
w

array([[ 1.1398773 , -7.461886  , -2.8746164 , -2.0423076 , -4.617762  ,
        -6.9565463 , -7.6526723 , -6.38876   , -7.2690034 ,  1.5022509 ,
        -1.6932162 , -5.357241  , -1.4137683 , -1.4419839 , -1.6191491 ,
        -2.8720467 , -1.4528283 , -1.5427355 ,  3.3935351 , -6.3151627 ,
        -2.0923586 , -2.7431886 ,  0.91604304, -1.4157599 , -2.7947814 ,
        -2.2340095 , -5.175427  , -3.8806598 ,  4.002934  , -7.033275  ,
        -1.5187911 , -5.6146493 , -4.574011  , -1.7219036 , -7.287285  ,
        -6.8696575 ,  4.1530886 ,  0.7346284 , -6.8092165 , -7.4656944 ,
        -1.4122367 , -5.0790744 , -1.6045403 , -1.464305  , -1.5894854 ,
         0.88926655, -1.8951468 , -1.4938788 , -0.20656097,  2.834508  ,
        -1.6743636 , -8.585489  , -3.2368352 , -6.923969  , -2.0250344 ,
        -7.067562  , -5.2868686 , -1.5121167 , -1.7180508 , -2.6216035 ,
        -2.9166307 , -1.4358872 , -1.8916123 , -8.027511  , -2.4890194 ,
        -6.3489056 , -1.5601193 , -6.4288864 , -1.6

In [8]:
w, b = dense2.get_weights()
w

array([[ 1.2785559 ],
       [-1.6403732 ],
       [-0.23154464],
       [-0.07400975],
       [-0.65789443],
       [-1.45005   ],
       [ 1.7654743 ],
       [-1.220138  ],
       [-1.6665671 ],
       [ 0.996781  ],
       [ 0.1396095 ],
       [ 0.70084536],
       [ 0.04088701],
       [ 0.17809719],
       [ 0.13134477],
       [-0.21031061],
       [ 0.06390435],
       [ 0.07979653],
       [ 2.3871672 ],
       [ 1.1332152 ],
       [-0.07558368],
       [ 0.68180597],
       [ 1.1486299 ],
       [ 0.07654568],
       [ 0.64900595],
       [ 0.22007234],
       [-0.8261996 ],
       [-0.4561374 ],
       [ 2.2273993 ],
       [ 1.5594468 ],
       [ 0.09716774],
       [ 1.0083978 ],
       [-0.6285664 ],
       [ 0.01487569],
       [ 1.5148369 ],
       [ 1.2382363 ],
       [ 2.1238956 ],
       [-2.8265479 ],
       [-1.3307811 ],
       [-1.6051621 ],
       [ 0.16956823],
       [ 0.92802143],
       [ 0.00610806],
       [ 0.06653949],
       [ 0.1990523 ],
       [-0

In [ ]:
# 4x2  2x100  = 4x100  100x1 = 4x1

In [10]:
#다른 방식
modelNN = Sequential()

modelNN.add( Dense( units=64, input_dim=2 ,activation="sigmoid") )
modelNN.add( Dense( units=32, activation="sigmoid") ) #input_dim 생략 가능
modelNN.add( Dense( units=1,  activation="sigmoid") )
modelNN.compile( loss="binary_crossentropy" ,optimizer=Adam(0.1), metrics=['acc'] )
h = modelNN.fit( x_data, y_data, epochs=1000)

Epoch 1/1000
1/1 [==============================] - 0s 255ms/step - loss: 0.7272 - acc: 0.5000
Epoch 2/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.9334 - acc: 0.5000
Epoch 3/1000
1/1 [==============================] - 0s 997us/step - loss: 1.4853 - acc: 0.5000
Epoch 4/1000
1/1 [==============================] - 0s 997us/step - loss: 1.0340 - acc: 0.5000
Epoch 5/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.7962 - acc: 0.5000
Epoch 6/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.7020 - acc: 0.5000
Epoch 7/1000
1/1 [==============================] - 0s 997us/step - loss: 0.7059 - acc: 0.5000
Epoch 8/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.7554 - acc: 0.5000
Epoch 9/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.7983 - acc: 0.5000
Epoch 10/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.8163 - acc: 0.5000
Epoch 11/1000
1/1 [==============================] - 0s 2ms/s

1/1 [==============================] - 0s 997us/step - loss: 0.0309 - acc: 1.0000
Epoch 88/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0297 - acc: 1.0000
Epoch 89/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0286 - acc: 1.0000
Epoch 90/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0276 - acc: 1.0000
Epoch 91/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0266 - acc: 1.0000
Epoch 92/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0257 - acc: 1.0000
Epoch 93/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0249 - acc: 1.0000
Epoch 94/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0241 - acc: 1.0000
Epoch 95/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0234 - acc: 1.0000
Epoch 96/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0227 - acc: 1.0000
Epoch 97/1000
1/1 [==============================] - 0s 2ms/st

1/1 [==============================] - 0s 997us/step - loss: 0.0076 - acc: 1.0000
Epoch 173/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0075 - acc: 1.0000
Epoch 174/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0074 - acc: 1.0000
Epoch 175/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0074 - acc: 1.0000
Epoch 176/1000
1/1 [==============================] - 0s 996us/step - loss: 0.0073 - acc: 1.0000
Epoch 177/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0072 - acc: 1.0000
Epoch 178/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0072 - acc: 1.0000
Epoch 179/1000
1/1 [==============================] - 0s 999us/step - loss: 0.0071 - acc: 1.0000
Epoch 180/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0071 - acc: 1.0000
Epoch 181/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0070 - acc: 1.0000
Epoch 182/1000
1/1 [==============================]

1/1 [==============================] - 0s 999us/step - loss: 0.0041 - acc: 1.0000
Epoch 258/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0041 - acc: 1.0000
Epoch 259/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0040 - acc: 1.0000
Epoch 260/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0040 - acc: 1.0000
Epoch 261/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0040 - acc: 1.0000
Epoch 262/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0040 - acc: 1.0000
Epoch 263/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0039 - acc: 1.0000
Epoch 264/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0039 - acc: 1.0000
Epoch 265/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0039 - acc: 1.0000
Epoch 266/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0039 - acc: 1.0000
Epoch 267/1000
1/1 [==============================] - 0

1/1 [==============================] - 0s 1ms/step - loss: 0.0026 - acc: 1.0000
Epoch 343/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0026 - acc: 1.0000
Epoch 344/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0026 - acc: 1.0000
Epoch 345/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0026 - acc: 1.0000
Epoch 346/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0026 - acc: 1.0000
Epoch 347/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0026 - acc: 1.0000
Epoch 348/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0026 - acc: 1.0000
Epoch 349/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0026 - acc: 1.0000
Epoch 350/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0026 - acc: 1.0000
Epoch 351/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0025 - acc: 1.0000
Epoch 352/1000
1/1 [==============================] - 0s 997us/

Epoch 428/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0019 - acc: 1.0000
Epoch 429/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0019 - acc: 1.0000
Epoch 430/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0019 - acc: 1.0000
Epoch 431/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0019 - acc: 1.0000
Epoch 432/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0018 - acc: 1.0000
Epoch 433/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0018 - acc: 1.0000
Epoch 434/1000
1/1 [==============================] - 0s 996us/step - loss: 0.0018 - acc: 1.0000
Epoch 435/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0018 - acc: 1.0000
Epoch 436/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0018 - acc: 1.0000
Epoch 437/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.0018 - acc: 1.0000
Epoch 438/1000
1/1 [========================

1/1 [==============================] - 0s 997us/step - loss: 0.0014 - acc: 1.0000
Epoch 514/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0014 - acc: 1.0000
Epoch 515/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0014 - acc: 1.0000
Epoch 516/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0014 - acc: 1.0000
Epoch 517/1000
1/1 [==============================] - 0s 937us/step - loss: 0.0014 - acc: 1.0000
Epoch 518/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0014 - acc: 1.0000
Epoch 519/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0014 - acc: 1.0000
Epoch 520/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0014 - acc: 1.0000
Epoch 521/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0014 - acc: 1.0000
Epoch 522/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0014 - acc: 1.0000
Epoch 523/1000
1/1 [==============================] -

1/1 [==============================] - 0s 1ms/step - loss: 0.0011 - acc: 1.0000
Epoch 599/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0011 - acc: 1.0000
Epoch 600/1000
1/1 [==============================] - 0s 964us/step - loss: 0.0011 - acc: 1.0000
Epoch 601/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0011 - acc: 1.0000
Epoch 602/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0011 - acc: 1.0000
Epoch 603/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0011 - acc: 1.0000
Epoch 604/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0011 - acc: 1.0000
Epoch 605/1000
1/1 [==============================] - 0s 996us/step - loss: 0.0011 - acc: 1.0000
Epoch 606/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.0011 - acc: 1.0000
Epoch 607/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0011 - acc: 1.0000
Epoch 608/1000
1/1 [==============================] - 0s 

1/1 [==============================] - 0s 2ms/step - loss: 9.0898e-04 - acc: 1.0000
Epoch 682/1000
1/1 [==============================] - 0s 998us/step - loss: 9.0686e-04 - acc: 1.0000
Epoch 683/1000
1/1 [==============================] - 0s 998us/step - loss: 9.0476e-04 - acc: 1.0000
Epoch 684/1000
1/1 [==============================] - 0s 2ms/step - loss: 9.0267e-04 - acc: 1.0000
Epoch 685/1000
1/1 [==============================] - 0s 997us/step - loss: 9.0058e-04 - acc: 1.0000
Epoch 686/1000
1/1 [==============================] - 0s 2ms/step - loss: 8.9850e-04 - acc: 1.0000
Epoch 687/1000
1/1 [==============================] - 0s 998us/step - loss: 8.9643e-04 - acc: 1.0000
Epoch 688/1000
1/1 [==============================] - 0s 997us/step - loss: 8.9436e-04 - acc: 1.0000
Epoch 689/1000
1/1 [==============================] - 0s 2ms/step - loss: 8.9230e-04 - acc: 1.0000
Epoch 690/1000
1/1 [==============================] - 0s 997us/step - loss: 8.9025e-04 - acc: 1.0000
Epoch 691/100

1/1 [==============================] - 0s 997us/step - loss: 7.5845e-04 - acc: 1.0000
Epoch 764/1000
1/1 [==============================] - 0s 2ms/step - loss: 7.5687e-04 - acc: 1.0000
Epoch 765/1000
1/1 [==============================] - 0s 2ms/step - loss: 7.5528e-04 - acc: 1.0000
Epoch 766/1000
1/1 [==============================] - 0s 996us/step - loss: 7.5370e-04 - acc: 1.0000
Epoch 767/1000
1/1 [==============================] - 0s 2ms/step - loss: 7.5213e-04 - acc: 1.0000
Epoch 768/1000
1/1 [==============================] - 0s 997us/step - loss: 7.5056e-04 - acc: 1.0000
Epoch 769/1000
1/1 [==============================] - 0s 997us/step - loss: 7.4900e-04 - acc: 1.0000
Epoch 770/1000
1/1 [==============================] - 0s 2ms/step - loss: 7.4744e-04 - acc: 1.0000
Epoch 771/1000
1/1 [==============================] - 0s 997us/step - loss: 7.4589e-04 - acc: 1.0000
Epoch 772/1000
1/1 [==============================] - 0s 998us/step - loss: 7.4434e-04 - acc: 1.0000
Epoch 773/100

1/1 [==============================] - 0s 1ms/step - loss: 6.4359e-04 - acc: 1.0000
Epoch 846/1000
1/1 [==============================] - 0s 2ms/step - loss: 6.4236e-04 - acc: 1.0000
Epoch 847/1000
1/1 [==============================] - 0s 999us/step - loss: 6.4113e-04 - acc: 1.0000
Epoch 848/1000
1/1 [==============================] - 0s 2ms/step - loss: 6.3991e-04 - acc: 1.0000
Epoch 849/1000
1/1 [==============================] - 0s 997us/step - loss: 6.3869e-04 - acc: 1.0000
Epoch 850/1000
1/1 [==============================] - 0s 997us/step - loss: 6.3747e-04 - acc: 1.0000
Epoch 851/1000
1/1 [==============================] - 0s 998us/step - loss: 6.3626e-04 - acc: 1.0000
Epoch 852/1000
1/1 [==============================] - 0s 997us/step - loss: 6.3505e-04 - acc: 1.0000
Epoch 853/1000
1/1 [==============================] - 0s 2ms/step - loss: 6.3385e-04 - acc: 1.0000
Epoch 854/1000
1/1 [==============================] - 0s 2ms/step - loss: 6.3265e-04 - acc: 1.0000
Epoch 855/1000


1/1 [==============================] - 0s 999us/step - loss: 5.5363e-04 - acc: 1.0000
Epoch 928/1000
1/1 [==============================] - 0s 2ms/step - loss: 5.5266e-04 - acc: 1.0000
Epoch 929/1000
1/1 [==============================] - 0s 1ms/step - loss: 5.5169e-04 - acc: 1.0000
Epoch 930/1000
1/1 [==============================] - 0s 2ms/step - loss: 5.5072e-04 - acc: 1.0000
Epoch 931/1000
1/1 [==============================] - 0s 998us/step - loss: 5.4975e-04 - acc: 1.0000
Epoch 932/1000
1/1 [==============================] - 0s 998us/step - loss: 5.4879e-04 - acc: 1.0000
Epoch 933/1000
1/1 [==============================] - 0s 997us/step - loss: 5.4782e-04 - acc: 1.0000
Epoch 934/1000
1/1 [==============================] - 0s 2ms/step - loss: 5.4687e-04 - acc: 1.0000
Epoch 935/1000
1/1 [==============================] - 0s 997us/step - loss: 5.4591e-04 - acc: 1.0000
Epoch 936/1000
1/1 [==============================] - 0s 2ms/step - loss: 5.4495e-04 - acc: 1.0000
Epoch 937/1000


In [18]:
(modelNN.predict(x_data) > 0.5)

array([[False],
       [ True],
       [ True],
       [False]])

In [11]:
modelNN.layers

In [15]:
w, b = modelNN.layers[0].get_weights()
w

array([[-3.082867  , -2.1094048 , -2.9078996 , -3.4814858 , -3.314244  ,
        -4.2811327 , -3.546597  , -2.7099404 ,  4.6578436 , -1.4015538 ,
        -3.097973  , -2.5292125 , -2.9863982 , -0.23225577, -2.9071875 ,
        -2.8218904 , -0.5581507 , -2.396793  , -3.972141  , -2.2207668 ,
        -3.1815438 , -2.4598174 , -3.8314612 , -3.3421035 , -1.6764555 ,
        -2.332776  , -2.490134  , -0.19854915, -2.9015617 , -0.8645208 ,
        -3.465594  , -1.2095956 , -2.6769023 , -1.6224954 , -1.1969215 ,
        -4.1450067 , -3.6639576 , -3.1199229 , -5.0717    , -4.0757732 ,
        -0.49846312, -2.9925272 , -2.7013123 , -3.394151  , -3.4473195 ,
        -0.5680939 , -3.7219334 , -0.58656645, -4.0372334 , -4.0419893 ,
        -3.1650639 , -2.9000607 , -2.403754  , -1.031198  , -4.0292797 ,
        -1.803571  , -0.6886285 , -2.2284703 , -0.76375866, -3.4196258 ,
        -3.1806214 , -1.837216  , -3.3353484 , -3.416426  ],
       [-3.316334  , -3.7999694 , -2.3873808 , -3.4953423 , -3.

In [16]:
w, b = modelNN.layers[1].get_weights()
w

array([[ 0.33472434, -0.92954266, -0.49402836, ..., -0.69573516,
        -0.6961548 , -0.5707266 ],
       [ 0.6400926 , -0.5197193 , -0.8274933 , ..., -0.41476667,
        -1.0594199 , -0.6635279 ],
       [ 0.40547097, -0.42500412, -0.77415556, ..., -0.4473298 ,
        -1.213997  , -0.89675874],
       ...,
       [ 0.0810698 ,  0.42216897, -0.814945  , ...,  0.24900645,
        -0.89801854, -0.48496777],
       [ 0.55822915, -0.98727465, -0.73697907, ..., -1.1487032 ,
        -1.2700083 , -0.7173974 ],
       [ 0.41097856, -1.0242949 , -0.91675705, ..., -1.1422963 ,
        -0.9499098 , -0.66613716]], dtype=float32)