In [32]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.style.use("ggplot")

from tensorflow.keras.optimizers import Adam
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from tensorflow.keras.optimizers import Adam

In [2]:
#공부한 시간, 출석 일수
x_data = np.array( [[1,3],[2,2],[3,1],[4,6],[5,5],[6,4]] )
y_data = np.array( [[0],[0],[0],[1],[1],[1]] )

In [3]:
x = tf.constant(x_data, tf.float32)
y = tf.constant(y_data, tf.float32)

In [4]:
# xavier, he (최적의 초기화 알고리즘)
initX = tf.initializers.GlorotUniform() #xavier
w = tf.Variable( initX( shape = [2,1] ) )
b = tf.Variable( initX( shape = [1] ) )

In [5]:
def compute_loss():
    z = tf.matmul(x, w) + b
#     hx = tf.nn.sigmoid(z) #0 ~ 1
    cost_i = tf.nn.sigmoid_cross_entropy_with_logits(labels = y, logits = z)
    cost = tf.reduce_mean( cost_i )
    #cost가 미분 불가하기 때문에 log함수 적용
    #  hx = tf.matmul( x, w) + b
    #  cost = tf.reduce_mean( (hx-y)**2) -> 연속데이터 경우
    return cost

In [8]:
optimizer = Adam(0.1)
for i in range(1000):
    optimizer.minimize(compute_loss, var_list = [w, b] )
    print(i, 'cost : ', compute_loss().numpy() )

0 cost :  0.9660614
1 cost :  0.94940144
2 cost :  0.9135892
3 cost :  0.8721068
4 cost :  0.8375003
5 cost :  0.8096326
6 cost :  0.78213793
7 cost :  0.7520874
8 cost :  0.72153276
9 cost :  0.6941897
10 cost :  0.67153597
11 cost :  0.65115917
12 cost :  0.629945
13 cost :  0.6081286
14 cost :  0.5881705
15 cost :  0.571155
16 cost :  0.55579215
17 cost :  0.5403567
18 cost :  0.5245381
19 cost :  0.5093024
20 cost :  0.49543145
21 cost :  0.48247716
22 cost :  0.46934557
23 cost :  0.45566705
24 cost :  0.44203892
25 cost :  0.42908037
26 cost :  0.41674197
27 cost :  0.40455472
28 cost :  0.3922654
29 cost :  0.38008752
30 cost :  0.368413
31 cost :  0.3573853
32 cost :  0.3468043
33 cost :  0.33642927
34 cost :  0.32627398
35 cost :  0.3165474
36 cost :  0.3073825
37 cost :  0.2987079
38 cost :  0.29036257
39 cost :  0.28226855
40 cost :  0.27447373
41 cost :  0.2670544
42 cost :  0.2600072
43 cost :  0.25324354
44 cost :  0.24667709
45 cost :  0.24029498
46 cost :  0.2341383
47 

392 cost :  0.011350443
393 cost :  0.01130671
394 cost :  0.011263244
395 cost :  0.011220048
396 cost :  0.011177123
397 cost :  0.011134458
398 cost :  0.01109206
399 cost :  0.011049919
400 cost :  0.011008036
401 cost :  0.01096641
402 cost :  0.010925037
403 cost :  0.010883917
404 cost :  0.010843043
405 cost :  0.010802418
406 cost :  0.010762035
407 cost :  0.0107219
408 cost :  0.0106820045
409 cost :  0.010642346
410 cost :  0.010602924
411 cost :  0.010563739
412 cost :  0.010524788
413 cost :  0.010486067
414 cost :  0.010447577
415 cost :  0.010409313
416 cost :  0.010371276
417 cost :  0.010333462
418 cost :  0.010295868
419 cost :  0.010258494
420 cost :  0.010221342
421 cost :  0.010184406
422 cost :  0.010147679
423 cost :  0.010111169
424 cost :  0.01007487
425 cost :  0.010038783
426 cost :  0.010002901
427 cost :  0.009967223
428 cost :  0.0099317515
429 cost :  0.009896484
430 cost :  0.009861417
431 cost :  0.009826549
432 cost :  0.009791878
433 cost :  0.009757

778 cost :  0.003909111
779 cost :  0.003901073
780 cost :  0.0038930606
781 cost :  0.0038850752
782 cost :  0.0038771117
783 cost :  0.003869176
784 cost :  0.0038612646
785 cost :  0.0038533788
786 cost :  0.00384552
787 cost :  0.003837684
788 cost :  0.003829873
789 cost :  0.0038220882
790 cost :  0.0038143247
791 cost :  0.0038065882
792 cost :  0.003798876
793 cost :  0.0037911881
794 cost :  0.0037835247
795 cost :  0.0037758835
796 cost :  0.0037682673
797 cost :  0.003760676
798 cost :  0.0037531077
799 cost :  0.003745564
800 cost :  0.003738042
801 cost :  0.003730545
802 cost :  0.0037230717
803 cost :  0.0037156197
804 cost :  0.0037081912
805 cost :  0.003700788
806 cost :  0.0036934044
807 cost :  0.003686046
808 cost :  0.0036787118
809 cost :  0.0036713972
810 cost :  0.003664108
811 cost :  0.0036568388
812 cost :  0.0036495924
813 cost :  0.0036423684
814 cost :  0.0036351674
815 cost :  0.0036279883
816 cost :  0.0036208306
817 cost :  0.0036136955
818 cost :  0.0

In [9]:
w.numpy()

array([[2.0109212],
       [2.0188668]], dtype=float32)

In [18]:
#예측함수 생성
def hxfn(x_data):
    xd = tf.constant(x_data, tf.float32)
    z = tf.matmul(xd, w) + b
    hx = tf.nn.sigmoid(z)
    return (hx.numpy() > 0.5) + 0 #합격(1)/ 불합격(0) 출력
#     return z.numpy(), hx.numpy()

In [19]:
#4시간 공부, 5시간 출석
hxfn( [[4, 5]] ) c

array([[1]])

In [20]:
#2시간 공부, 2시간 출석
hxfn( [[2, 2]] ) 

array([[0]])

In [16]:
True + 1

2

In [17]:
False + 1

1

In [21]:
hxfn( [[2, 3], [5, 6]] ) 

array([[0],
       [1]])

In [22]:
x_data.shape

(6, 2)

In [25]:
pred = hxfn(x_data)

In [24]:
y_data

array([[0],
       [0],
       [0],
       [1],
       [1],
       [1]])

In [26]:
pred == y_data

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True]])

In [27]:
(pred == y_data).mean()

1.0

In [29]:
#정확도 함수 생성
def accFn(x_data):
    pred = hxfn(x_data)
    return (pred == y_data).mean()

In [30]:
accFn(x_data)

1.0