In [26]:
from numpy import array
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, SimpleRNN, GRU, TimeDistributed

#### Many to One

In [2]:
x = array([[1,2,3], [2,3,4], [3,4,5], [4,5,6]]) #[1, 2, 3]으로 '4' 예측, [2, 3, 4]로 '5' 예측, ...
y = array([4,5,6,7])
print('x shape : ', x.shape) # (4,3)
print('y shape : ', y.shape) # (4,)
print(x)

x shape :  (4, 3)
y shape :  (4,)
[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


In [3]:
x = x.reshape(4, 3, 1) # (batch size, sequence length, feature size)
x
#       □
# □ □ □
# □ □ □
# □ □ □
# □ □ □

array([[[1],
        [2],
        [3]],

       [[2],
        [3],
        [4]],

       [[3],
        [4],
        [5]],

       [[4],
        [5],
        [6]]])

In [14]:
model = Sequential()                    
                 #이 값에 따라 rnn 셀의 크기가 결정됨
                 #    ↓                    sequence length, feature size
model.add( SimpleRNN( 8, activation='relu', input_shape=(3, 1) ) )
# model.add( Dense( units=16 ) )
model.add( Dense( units=1 ) )
model.compile( loss='mse', optimizer='adam' )
model.fit(x, y, epochs=1000)

Epoch 1/1000
1/1 [==============================] - 0s 403ms/step - loss: 37.9012
Epoch 2/1000
1/1 [==============================] - 0s 997us/step - loss: 37.8212
Epoch 3/1000
1/1 [==============================] - 0s 998us/step - loss: 37.7417
Epoch 4/1000
1/1 [==============================] - 0s 2ms/step - loss: 37.6625
Epoch 5/1000
1/1 [==============================] - 0s 998us/step - loss: 37.5838
Epoch 6/1000
1/1 [==============================] - 0s 2ms/step - loss: 37.5055
Epoch 7/1000
1/1 [==============================] - 0s 2ms/step - loss: 37.4276
Epoch 8/1000
1/1 [==============================] - 0s 997us/step - loss: 37.3501
Epoch 9/1000
1/1 [==============================] - 0s 2ms/step - loss: 37.2731
Epoch 10/1000
1/1 [==============================] - 0s 999us/step - loss: 37.1965
Epoch 11/1000
1/1 [==============================] - 0s 2ms/step - loss: 37.1203
Epoch 12/1000
1/1 [==============================] - 0s 2ms/step - loss: 37.0446
Epoch 13/1000
1/1 [======

1/1 [==============================] - 0s 2ms/step - loss: 31.9081
Epoch 102/1000
1/1 [==============================] - 0s 2ms/step - loss: 31.8641
Epoch 103/1000
1/1 [==============================] - 0s 1ms/step - loss: 31.8203
Epoch 104/1000
1/1 [==============================] - 0s 2ms/step - loss: 31.7767
Epoch 105/1000
1/1 [==============================] - 0s 2ms/step - loss: 31.7334
Epoch 106/1000
1/1 [==============================] - 0s 998us/step - loss: 31.6901
Epoch 107/1000
1/1 [==============================] - 0s 996us/step - loss: 31.6471
Epoch 108/1000
1/1 [==============================] - 0s 997us/step - loss: 31.6043
Epoch 109/1000
1/1 [==============================] - 0s 2ms/step - loss: 31.5616
Epoch 110/1000
1/1 [==============================] - 0s 997us/step - loss: 31.5191
Epoch 111/1000
1/1 [==============================] - 0s 997us/step - loss: 31.4768
Epoch 112/1000
1/1 [==============================] - 0s 2ms/step - loss: 31.4346
Epoch 113/1000
1/1 [=

1/1 [==============================] - 0s 996us/step - loss: 29.4217
Epoch 200/1000
1/1 [==============================] - 0s 998us/step - loss: 29.4116
Epoch 201/1000
1/1 [==============================] - 0s 997us/step - loss: 29.4014
Epoch 202/1000
1/1 [==============================] - 0s 2ms/step - loss: 29.3913
Epoch 203/1000
1/1 [==============================] - 0s 2ms/step - loss: 29.3811
Epoch 204/1000
1/1 [==============================] - 0s 998us/step - loss: 29.3710
Epoch 205/1000
1/1 [==============================] - 0s 2ms/step - loss: 29.3609
Epoch 206/1000
1/1 [==============================] - 0s 997us/step - loss: 29.3507
Epoch 207/1000
1/1 [==============================] - 0s 997us/step - loss: 29.3406
Epoch 208/1000
1/1 [==============================] - 0s 998us/step - loss: 29.3305
Epoch 209/1000
1/1 [==============================] - 0s 2ms/step - loss: 29.3203
Epoch 210/1000
1/1 [==============================] - 0s 2ms/step - loss: 29.3102
Epoch 211/1000
1/

Epoch 298/1000
1/1 [==============================] - 0s 998us/step - loss: 28.4250
Epoch 299/1000
1/1 [==============================] - 0s 2ms/step - loss: 28.4150
Epoch 300/1000
1/1 [==============================] - 0s 996us/step - loss: 28.4050
Epoch 301/1000
1/1 [==============================] - 0s 997us/step - loss: 28.3950
Epoch 302/1000
1/1 [==============================] - 0s 2ms/step - loss: 28.3851
Epoch 303/1000
1/1 [==============================] - 0s 2ms/step - loss: 28.3751
Epoch 304/1000
1/1 [==============================] - 0s 2ms/step - loss: 28.3651
Epoch 305/1000
1/1 [==============================] - 0s 2ms/step - loss: 28.3552
Epoch 306/1000
1/1 [==============================] - 0s 997us/step - loss: 28.3452
Epoch 307/1000
1/1 [==============================] - 0s 998us/step - loss: 28.3352
Epoch 308/1000
1/1 [==============================] - 0s 996us/step - loss: 28.3253
Epoch 309/1000
1/1 [==============================] - 0s 2ms/step - loss: 28.3153
Epoc

1/1 [==============================] - 0s 2ms/step - loss: 27.4569
Epoch 397/1000
1/1 [==============================] - 0s 2ms/step - loss: 27.4472
Epoch 398/1000
1/1 [==============================] - 0s 2ms/step - loss: 27.4374
Epoch 399/1000
1/1 [==============================] - 0s 998us/step - loss: 27.4276
Epoch 400/1000
1/1 [==============================] - 0s 1ms/step - loss: 27.4179
Epoch 401/1000
1/1 [==============================] - 0s 998us/step - loss: 27.4081
Epoch 402/1000
1/1 [==============================] - 0s 2ms/step - loss: 27.3984
Epoch 403/1000
1/1 [==============================] - 0s 2ms/step - loss: 27.3886
Epoch 404/1000
1/1 [==============================] - 0s 2ms/step - loss: 27.3789
Epoch 405/1000
1/1 [==============================] - 0s 2ms/step - loss: 27.3691
Epoch 406/1000
1/1 [==============================] - 0s 997us/step - loss: 27.3594
Epoch 407/1000
1/1 [==============================] - 0s 998us/step - loss: 27.3496
Epoch 408/1000
1/1 [===

1/1 [==============================] - 0s 997us/step - loss: 26.5009
Epoch 496/1000
1/1 [==============================] - 0s 2ms/step - loss: 26.4914
Epoch 497/1000
1/1 [==============================] - 0s 2ms/step - loss: 26.4818
Epoch 498/1000
1/1 [==============================] - 0s 2ms/step - loss: 26.4723
Epoch 499/1000
1/1 [==============================] - 0s 997us/step - loss: 26.4628
Epoch 500/1000
1/1 [==============================] - 0s 998us/step - loss: 26.4532
Epoch 501/1000
1/1 [==============================] - 0s 2ms/step - loss: 26.4437
Epoch 502/1000
1/1 [==============================] - 0s 2ms/step - loss: 26.4342
Epoch 503/1000
1/1 [==============================] - 0s 2ms/step - loss: 26.4247
Epoch 504/1000
1/1 [==============================] - 0s 2ms/step - loss: 26.4151
Epoch 505/1000
1/1 [==============================] - 0s 998us/step - loss: 26.4056
Epoch 506/1000
1/1 [==============================] - 0s 998us/step - loss: 26.3961
Epoch 507/1000
1/1 [=

1/1 [==============================] - 0s 998us/step - loss: 25.5773
Epoch 594/1000
1/1 [==============================] - 0s 2ms/step - loss: 25.5679
Epoch 595/1000
1/1 [==============================] - 0s 2ms/step - loss: 25.5586
Epoch 596/1000
1/1 [==============================] - 0s 998us/step - loss: 25.5493
Epoch 597/1000
1/1 [==============================] - 0s 998us/step - loss: 25.5400
Epoch 598/1000
1/1 [==============================] - 0s 997us/step - loss: 25.5307
Epoch 599/1000
1/1 [==============================] - 0s 998us/step - loss: 25.5214
Epoch 600/1000
1/1 [==============================] - 0s 998us/step - loss: 25.5121
Epoch 601/1000
1/1 [==============================] - 0s 2ms/step - loss: 25.5029
Epoch 602/1000
1/1 [==============================] - 0s 2ms/step - loss: 25.4936
Epoch 603/1000
1/1 [==============================] - 0s 998us/step - loss: 25.4843
Epoch 604/1000
1/1 [==============================] - 0s 2ms/step - loss: 25.4750
Epoch 605/1000
1/

Epoch 692/1000
1/1 [==============================] - 0s 998us/step - loss: 24.6674
Epoch 693/1000
1/1 [==============================] - 0s 997us/step - loss: 24.6583
Epoch 694/1000
1/1 [==============================] - 0s 998us/step - loss: 24.6493
Epoch 695/1000
1/1 [==============================] - 0s 998us/step - loss: 24.6402
Epoch 696/1000
1/1 [==============================] - 0s 2ms/step - loss: 24.6311
Epoch 697/1000
1/1 [==============================] - 0s 2ms/step - loss: 24.6221
Epoch 698/1000
1/1 [==============================] - 0s 2ms/step - loss: 24.6130
Epoch 699/1000
1/1 [==============================] - 0s 2ms/step - loss: 24.6039
Epoch 700/1000
1/1 [==============================] - 0s 998us/step - loss: 24.5949
Epoch 701/1000
1/1 [==============================] - 0s 997us/step - loss: 24.5858
Epoch 702/1000
1/1 [==============================] - 0s 997us/step - loss: 24.5768
Epoch 703/1000
1/1 [==============================] - 0s 997us/step - loss: 24.5677


1/1 [==============================] - 0s 1ms/step - loss: 23.7897
Epoch 791/1000
1/1 [==============================] - 0s 998us/step - loss: 23.7809
Epoch 792/1000
1/1 [==============================] - 0s 998us/step - loss: 23.7720
Epoch 793/1000
1/1 [==============================] - 0s 2ms/step - loss: 23.7632
Epoch 794/1000
1/1 [==============================] - 0s 2ms/step - loss: 23.7544
Epoch 795/1000
1/1 [==============================] - 0s 2ms/step - loss: 23.7455
Epoch 796/1000
1/1 [==============================] - 0s 2ms/step - loss: 23.7367
Epoch 797/1000
1/1 [==============================] - 0s 2ms/step - loss: 23.7279
Epoch 798/1000
1/1 [==============================] - 0s 997us/step - loss: 23.7190
Epoch 799/1000
1/1 [==============================] - 0s 998us/step - loss: 23.7102
Epoch 800/1000
1/1 [==============================] - 0s 997us/step - loss: 23.7014
Epoch 801/1000
1/1 [==============================] - 0s 998us/step - loss: 23.6926
Epoch 802/1000
1/1 

1/1 [==============================] - 0s 998us/step - loss: 22.9347
Epoch 889/1000
1/1 [==============================] - 0s 2ms/step - loss: 22.9260
Epoch 890/1000
1/1 [==============================] - 0s 2ms/step - loss: 22.9174
Epoch 891/1000
1/1 [==============================] - 0s 2ms/step - loss: 22.9088
Epoch 892/1000
1/1 [==============================] - 0s 998us/step - loss: 22.9002
Epoch 893/1000
1/1 [==============================] - 0s 997us/step - loss: 22.8916
Epoch 894/1000
1/1 [==============================] - 0s 2ms/step - loss: 22.8830
Epoch 895/1000
1/1 [==============================] - 0s 998us/step - loss: 22.8744
Epoch 896/1000
1/1 [==============================] - 0s 997us/step - loss: 22.8658
Epoch 897/1000
1/1 [==============================] - 0s 1ms/step - loss: 22.8573
Epoch 898/1000
1/1 [==============================] - 0s 997us/step - loss: 22.8487
Epoch 899/1000
1/1 [==============================] - 0s 2ms/step - loss: 22.8401
Epoch 900/1000
1/1 

1/1 [==============================] - 0s 998us/step - loss: 22.1020
Epoch 987/1000
1/1 [==============================] - 0s 998us/step - loss: 22.0936
Epoch 988/1000
1/1 [==============================] - 0s 2ms/step - loss: 22.0852
Epoch 989/1000
1/1 [==============================] - 0s 2ms/step - loss: 22.0769
Epoch 990/1000
1/1 [==============================] - 0s 2ms/step - loss: 22.0685
Epoch 991/1000
1/1 [==============================] - 0s 2ms/step - loss: 22.0601
Epoch 992/1000
1/1 [==============================] - 0s 998us/step - loss: 22.0517
Epoch 993/1000
1/1 [==============================] - 0s 997us/step - loss: 22.0434
Epoch 994/1000
1/1 [==============================] - 0s 2ms/step - loss: 22.0350
Epoch 995/1000
1/1 [==============================] - 0s 2ms/step - loss: 22.0266
Epoch 996/1000
1/1 [==============================] - 0s 2ms/step - loss: 22.0183
Epoch 997/1000
1/1 [==============================] - 0s 2ms/step - loss: 22.0099
Epoch 998/1000
1/1 [===

In [15]:
model.layers

In [16]:
rnnW = model.layers[0].get_weights()
rnnW

[array([[-0.34274507, -0.5717715 , -0.03579533, -0.29132372, -0.17718112,
         -0.43195555, -0.7604387 ,  0.01886906]], dtype=float32),
 array([[ 0.7030363 ,  0.20444573, -0.38221928,  0.35575026, -0.11433155,
          0.29932842, -0.26689178, -0.13187736],
        [ 0.38583624, -0.37184426, -0.10559628, -0.78532845, -0.08271816,
          0.19798532,  0.154232  , -0.12305611],
        [ 0.21620847, -0.19389799, -0.23156166, -0.01212669,  0.79863375,
         -0.32525545, -0.12815145,  0.31915522],
        [ 0.05142178, -0.17878048, -0.12947202,  0.12338728, -0.32017452,
          0.17753085,  0.26230943,  0.85473424],
        [-0.27352944,  0.3396601 , -0.7841754 , -0.13568392, -0.03430199,
         -0.15681352,  0.37330174, -0.1065373 ],
        [-0.47247407, -0.38650674, -0.3104173 ,  0.06343973,  0.15318558,
          0.59936553, -0.37498924, -0.06062578],
        [-0.03311477, -0.3999155 , -0.24482876,  0.01914759, -0.4619504 ,
         -0.58926755, -0.46602565, -0.02913647],

#### rnn학습 weight는 3개

In [17]:
rnnW[0].shape

(1, 8)

In [18]:
rnnW[1].shape

(8, 8)

In [19]:
rnnW[2].shape

(8,)

In [20]:
w, b = model.layers[1].get_weights()

In [21]:
w.shape

(8, 1)

#### Many to Many

In [22]:
import numpy as np

In [23]:
X = list()
Y = list()
X = [x for x in range(5, 301, 5)]
Y = [y for y in range(20, 316, 5)]

X = np.array(X).reshape(20, 3, 1)
Y = np.array(Y).reshape(20, 3, 1)

In [24]:
X

array([[[  5],
        [ 10],
        [ 15]],

       [[ 20],
        [ 25],
        [ 30]],

       [[ 35],
        [ 40],
        [ 45]],

       [[ 50],
        [ 55],
        [ 60]],

       [[ 65],
        [ 70],
        [ 75]],

       [[ 80],
        [ 85],
        [ 90]],

       [[ 95],
        [100],
        [105]],

       [[110],
        [115],
        [120]],

       [[125],
        [130],
        [135]],

       [[140],
        [145],
        [150]],

       [[155],
        [160],
        [165]],

       [[170],
        [175],
        [180]],

       [[185],
        [190],
        [195]],

       [[200],
        [205],
        [210]],

       [[215],
        [220],
        [225]],

       [[230],
        [235],
        [240]],

       [[245],
        [250],
        [255]],

       [[260],
        [265],
        [270]],

       [[275],
        [280],
        [285]],

       [[290],
        [295],
        [300]]])

In [25]:
Y

array([[[ 20],
        [ 25],
        [ 30]],

       [[ 35],
        [ 40],
        [ 45]],

       [[ 50],
        [ 55],
        [ 60]],

       [[ 65],
        [ 70],
        [ 75]],

       [[ 80],
        [ 85],
        [ 90]],

       [[ 95],
        [100],
        [105]],

       [[110],
        [115],
        [120]],

       [[125],
        [130],
        [135]],

       [[140],
        [145],
        [150]],

       [[155],
        [160],
        [165]],

       [[170],
        [175],
        [180]],

       [[185],
        [190],
        [195]],

       [[200],
        [205],
        [210]],

       [[215],
        [220],
        [225]],

       [[230],
        [235],
        [240]],

       [[245],
        [250],
        [255]],

       [[260],
        [265],
        [270]],

       [[275],
        [280],
        [285]],

       [[290],
        [295],
        [300]],

       [[305],
        [310],
        [315]]])

In [27]:
model = Sequential()
model.add(LSTM(64, activation='relu', input_shape=(3, 1), return_sequences=True) )
model.add(TimeDistributed( Dense(1) ) )
#각 dense를 timestep별로 matmul하겠다
model.compile(loss='mse', optimizer='adam')
model.fit(X, Y, epochs=1000)

Epoch 1/1000
1/1 [==============================] - 1s 606ms/step - loss: 33714.9023
Epoch 2/1000
1/1 [==============================] - 0s 2ms/step - loss: 33455.5039
Epoch 3/1000
1/1 [==============================] - 0s 2ms/step - loss: 33187.4531
Epoch 4/1000
1/1 [==============================] - 0s 2ms/step - loss: 32915.4414
Epoch 5/1000
1/1 [==============================] - 0s 2ms/step - loss: 32651.4180
Epoch 6/1000
1/1 [==============================] - 0s 3ms/step - loss: 32400.5059
Epoch 7/1000
1/1 [==============================] - 0s 2ms/step - loss: 32154.1465
Epoch 8/1000
1/1 [==============================] - 0s 3ms/step - loss: 31915.8809
Epoch 9/1000
1/1 [==============================] - 0s 3ms/step - loss: 31680.4414
Epoch 10/1000
1/1 [==============================] - 0s 3ms/step - loss: 31442.7617
Epoch 11/1000
1/1 [==============================] - 0s 3ms/step - loss: 31197.3789
Epoch 12/1000
1/1 [==============================] - 0s 3ms/step - loss: 30940.1602

1/1 [==============================] - 0s 2ms/step - loss: 5099.0044
Epoch 100/1000
1/1 [==============================] - 0s 3ms/step - loss: 5014.2388
Epoch 101/1000
1/1 [==============================] - 0s 2ms/step - loss: 4934.6118
Epoch 102/1000
1/1 [==============================] - 0s 3ms/step - loss: 4857.7168
Epoch 103/1000
1/1 [==============================] - 0s 3ms/step - loss: 4782.9380
Epoch 104/1000
1/1 [==============================] - 0s 2ms/step - loss: 4709.6851
Epoch 105/1000
1/1 [==============================] - 0s 2ms/step - loss: 4637.7969
Epoch 106/1000
1/1 [==============================] - 0s 2ms/step - loss: 4569.5127
Epoch 107/1000
1/1 [==============================] - 0s 2ms/step - loss: 4509.7432
Epoch 108/1000
1/1 [==============================] - 0s 2ms/step - loss: 4439.7183
Epoch 109/1000
1/1 [==============================] - 0s 2ms/step - loss: 4378.0288
Epoch 110/1000
1/1 [==============================] - 0s 2ms/step - loss: 4319.0825
Epoch 1

1/1 [==============================] - 0s 3ms/step - loss: 574.9177
Epoch 197/1000
1/1 [==============================] - 0s 3ms/step - loss: 548.5007
Epoch 198/1000
1/1 [==============================] - 0s 3ms/step - loss: 523.7785
Epoch 199/1000
1/1 [==============================] - 0s 3ms/step - loss: 501.7978
Epoch 200/1000
1/1 [==============================] - 0s 2ms/step - loss: 478.5402
Epoch 201/1000
1/1 [==============================] - 0s 2ms/step - loss: 457.0435
Epoch 202/1000
1/1 [==============================] - 0s 2ms/step - loss: 432.9276
Epoch 203/1000
1/1 [==============================] - 0s 2ms/step - loss: 411.9189
Epoch 204/1000
1/1 [==============================] - 0s 2ms/step - loss: 392.2559
Epoch 205/1000
1/1 [==============================] - 0s 2ms/step - loss: 372.9140
Epoch 206/1000
1/1 [==============================] - 0s 2ms/step - loss: 353.7699
Epoch 207/1000
1/1 [==============================] - 0s 3ms/step - loss: 335.0049
Epoch 208/1000
1/1 

1/1 [==============================] - 0s 2ms/step - loss: 32.0865
Epoch 296/1000
1/1 [==============================] - 0s 2ms/step - loss: 31.9924
Epoch 297/1000
1/1 [==============================] - 0s 2ms/step - loss: 31.8781
Epoch 298/1000
1/1 [==============================] - 0s 2ms/step - loss: 31.7353
Epoch 299/1000
1/1 [==============================] - 0s 2ms/step - loss: 31.5951
Epoch 300/1000
1/1 [==============================] - 0s 2ms/step - loss: 31.4125
Epoch 301/1000
1/1 [==============================] - 0s 2ms/step - loss: 31.2221
Epoch 302/1000
1/1 [==============================] - 0s 2ms/step - loss: 31.0186
Epoch 303/1000
1/1 [==============================] - 0s 2ms/step - loss: 30.7904
Epoch 304/1000
1/1 [==============================] - 0s 2ms/step - loss: 30.6013
Epoch 305/1000
1/1 [==============================] - 0s 2ms/step - loss: 30.4570
Epoch 306/1000
1/1 [==============================] - 0s 2ms/step - loss: 30.2671
Epoch 307/1000
1/1 [===========

1/1 [==============================] - 0s 2ms/step - loss: 17.6193
Epoch 396/1000
1/1 [==============================] - 0s 2ms/step - loss: 17.4908
Epoch 397/1000
1/1 [==============================] - 0s 2ms/step - loss: 17.3611
Epoch 398/1000
1/1 [==============================] - 0s 4ms/step - loss: 17.2297
Epoch 399/1000
1/1 [==============================] - 0s 3ms/step - loss: 17.1013
Epoch 400/1000
1/1 [==============================] - 0s 3ms/step - loss: 16.9748
Epoch 401/1000
1/1 [==============================] - 0s 3ms/step - loss: 16.8520
Epoch 402/1000
1/1 [==============================] - 0s 2ms/step - loss: 16.7316
Epoch 403/1000
1/1 [==============================] - 0s 2ms/step - loss: 16.6133
Epoch 404/1000
1/1 [==============================] - 0s 2ms/step - loss: 16.4981
Epoch 405/1000
1/1 [==============================] - 0s 2ms/step - loss: 16.3863
Epoch 406/1000
1/1 [==============================] - 0s 2ms/step - loss: 16.2855
Epoch 407/1000
1/1 [===========

1/1 [==============================] - 0s 2ms/step - loss: 7.2003
Epoch 496/1000
1/1 [==============================] - 0s 2ms/step - loss: 7.1622
Epoch 497/1000
1/1 [==============================] - 0s 2ms/step - loss: 7.1230
Epoch 498/1000
1/1 [==============================] - 0s 3ms/step - loss: 7.0827
Epoch 499/1000
1/1 [==============================] - 0s 2ms/step - loss: 7.0418
Epoch 500/1000
1/1 [==============================] - 0s 2ms/step - loss: 7.0027
Epoch 501/1000
1/1 [==============================] - 0s 3ms/step - loss: 6.9660
Epoch 502/1000
1/1 [==============================] - 0s 2ms/step - loss: 6.9307
Epoch 503/1000
1/1 [==============================] - 0s 3ms/step - loss: 6.8952
Epoch 504/1000
1/1 [==============================] - 0s 2ms/step - loss: 6.8588
Epoch 505/1000
1/1 [==============================] - 0s 2ms/step - loss: 6.8229
Epoch 506/1000
1/1 [==============================] - 0s 2ms/step - loss: 6.7887
Epoch 507/1000
1/1 [=======================

1/1 [==============================] - 0s 2ms/step - loss: 4.8485
Epoch 597/1000
1/1 [==============================] - 0s 3ms/step - loss: 4.8326
Epoch 598/1000
1/1 [==============================] - 0s 3ms/step - loss: 4.8165
Epoch 599/1000
1/1 [==============================] - 0s 3ms/step - loss: 4.8001
Epoch 600/1000
1/1 [==============================] - 0s 3ms/step - loss: 4.7835
Epoch 601/1000
1/1 [==============================] - 0s 2ms/step - loss: 4.7669
Epoch 602/1000
1/1 [==============================] - 0s 2ms/step - loss: 4.7505
Epoch 603/1000
1/1 [==============================] - 0s 2ms/step - loss: 4.7343
Epoch 604/1000
1/1 [==============================] - 0s 2ms/step - loss: 4.7184
Epoch 605/1000
1/1 [==============================] - 0s 2ms/step - loss: 4.7027
Epoch 606/1000
1/1 [==============================] - 0s 2ms/step - loss: 4.6869
Epoch 607/1000
1/1 [==============================] - 0s 2ms/step - loss: 4.6713
Epoch 608/1000
1/1 [=======================

1/1 [==============================] - 0s 2ms/step - loss: 3.2844
Epoch 698/1000
1/1 [==============================] - 0s 3ms/step - loss: 3.2717
Epoch 699/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.2590
Epoch 700/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.2462
Epoch 701/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.2335
Epoch 702/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.2208
Epoch 703/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.2081
Epoch 704/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.1957
Epoch 705/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.1834
Epoch 706/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.1712
Epoch 707/1000
1/1 [==============================] - 0s 3ms/step - loss: 3.1590
Epoch 708/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.1469
Epoch 709/1000
1/1 [=======================

1/1 [==============================] - 0s 3ms/step - loss: 2.2457
Epoch 799/1000
1/1 [==============================] - 0s 2ms/step - loss: 2.2376
Epoch 800/1000
1/1 [==============================] - 0s 2ms/step - loss: 2.2296
Epoch 801/1000
1/1 [==============================] - 0s 2ms/step - loss: 2.2215
Epoch 802/1000
1/1 [==============================] - 0s 2ms/step - loss: 2.2135
Epoch 803/1000
1/1 [==============================] - 0s 2ms/step - loss: 2.2056
Epoch 804/1000
1/1 [==============================] - 0s 2ms/step - loss: 2.1977
Epoch 805/1000
1/1 [==============================] - 0s 2ms/step - loss: 2.1898
Epoch 806/1000
1/1 [==============================] - 0s 2ms/step - loss: 2.1820
Epoch 807/1000
1/1 [==============================] - 0s 2ms/step - loss: 2.1742
Epoch 808/1000
1/1 [==============================] - 0s 2ms/step - loss: 2.1664
Epoch 809/1000
1/1 [==============================] - 0s 2ms/step - loss: 2.1587
Epoch 810/1000
1/1 [=======================

1/1 [==============================] - 0s 2ms/step - loss: 1.6022
Epoch 900/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.5974
Epoch 901/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.5926
Epoch 902/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.5879
Epoch 903/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.5832
Epoch 904/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.5786
Epoch 905/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.5739
Epoch 906/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.5693
Epoch 907/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.5647
Epoch 908/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.5601
Epoch 909/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.5556
Epoch 910/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.5511
Epoch 911/1000
1/1 [=======================

1/1 [==============================] - 0s 2ms/step - loss: 1.2306


In [28]:
arr = np.array( [300, 305, 310] )
model.predict( arr.reshape(1, 3, 1) )

array([[[316.27863],
        [320.28217],
        [325.02954]]], dtype=float32)