In [1]:
from numpy import array
import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, SimpleRNN, GRU

In [2]:
df = pd.read_csv('data/sample.csv', index_col='date')
df

x
date           
2021-01-01    1
2021-01-02    2
2021-01-03    3
2021-01-04    4
2021-01-05    5
...         ...
2021-04-06   96
2021-04-07   97
2021-04-08   98
2021-04-09   99
2021-04-10  100

[100 rows x 1 columns]

In [3]:
def split_xy1(dataset, time_steps):
    x, y = list(), list()
    for i in range(len(dataset)):
        end_number = i + time_steps
        if end_number > len(dataset) -1:
            break
        tmp_x, tmp_y = dataset[i:end_number], dataset[end_number]
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)

In [9]:
x, y = split_xy1( df['x'].values, 3 )
print(x)
print('===============')
print(y)

[[ 1  2  3]
 [ 2  3  4]
 [ 3  4  5]
 [ 4  5  6]
 [ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]
 [10 11 12]
 [11 12 13]
 [12 13 14]
 [13 14 15]
 [14 15 16]
 [15 16 17]
 [16 17 18]
 [17 18 19]
 [18 19 20]
 [19 20 21]
 [20 21 22]
 [21 22 23]
 [22 23 24]
 [23 24 25]
 [24 25 26]
 [25 26 27]
 [26 27 28]
 [27 28 29]
 [28 29 30]
 [29 30 31]
 [30 31 32]
 [31 32 33]
 [32 33 34]
 [33 34 35]
 [34 35 36]
 [35 36 37]
 [36 37 38]
 [37 38 39]
 [38 39 40]
 [39 40 41]
 [40 41 42]
 [41 42 43]
 [42 43 44]
 [43 44 45]
 [44 45 46]
 [45 46 47]
 [46 47 48]
 [47 48 49]
 [48 49 50]
 [49 50 51]
 [50 51 52]
 [51 52 53]
 [52 53 54]
 [53 54 55]
 [54 55 56]
 [55 56 57]
 [56 57 58]
 [57 58 59]
 [58 59 60]
 [59 60 61]
 [60 61 62]
 [61 62 63]
 [62 63 64]
 [63 64 65]
 [64 65 66]
 [65 66 67]
 [66 67 68]
 [67 68 69]
 [68 69 70]
 [69 70 71]
 [70 71 72]
 [71 72 73]
 [72 73 74]
 [73 74 75]
 [74 75 76]
 [75 76 77]
 [76 77 78]
 [77 78 79]
 [78 79 80]
 [79 80 81]
 [80 81 82]
 [81 82 83]
 [82 83 84]
 [83 84 85]
 [84

In [7]:
def split_xy2(dataset, time_steps, y_column):
    x, y = list(), list()
    for i in range(len(dataset)):
        x_end_number = i + time_steps
        y_end_number = x_end_number + y_column # 추가
        # if end_number > len(dataset) -1:
        # break
        if y_end_number > len(dataset): # 수정
            break
        tmp_x = dataset[i : x_end_number]
        tmp_y = dataset[x_end_number : y_end_number] # 수정
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)

In [8]:
x, y = split_xy2( df['x'].values, 3, 2 )
print(x)
print('===============')
print(y)

[[ 1  2  3]
 [ 2  3  4]
 [ 3  4  5]
 [ 4  5  6]
 [ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]
 [10 11 12]
 [11 12 13]
 [12 13 14]
 [13 14 15]
 [14 15 16]
 [15 16 17]
 [16 17 18]
 [17 18 19]
 [18 19 20]
 [19 20 21]
 [20 21 22]
 [21 22 23]
 [22 23 24]
 [23 24 25]
 [24 25 26]
 [25 26 27]
 [26 27 28]
 [27 28 29]
 [28 29 30]
 [29 30 31]
 [30 31 32]
 [31 32 33]
 [32 33 34]
 [33 34 35]
 [34 35 36]
 [35 36 37]
 [36 37 38]
 [37 38 39]
 [38 39 40]
 [39 40 41]
 [40 41 42]
 [41 42 43]
 [42 43 44]
 [43 44 45]
 [44 45 46]
 [45 46 47]
 [46 47 48]
 [47 48 49]
 [48 49 50]
 [49 50 51]
 [50 51 52]
 [51 52 53]
 [52 53 54]
 [53 54 55]
 [54 55 56]
 [55 56 57]
 [56 57 58]
 [57 58 59]
 [58 59 60]
 [59 60 61]
 [60 61 62]
 [61 62 63]
 [62 63 64]
 [63 64 65]
 [64 65 66]
 [65 66 67]
 [66 67 68]
 [67 68 69]
 [68 69 70]
 [69 70 71]
 [70 71 72]
 [71 72 73]
 [72 73 74]
 [73 74 75]
 [74 75 76]
 [75 76 77]
 [76 77 78]
 [77 78 79]
 [78 79 80]
 [79 80 81]
 [80 81 82]
 [81 82 83]
 [82 83 84]
 [83 84 85]
 [84

#### 3개의 타임스텝으로 rnn 학습하여 461, 360, 432인 경우의 예측값 구하기

In [12]:
df2 = pd.read_csv('data/international-airline-passengers.txt', index_col='time')
df2

passengers
time               
1949-01         112
1949-02         118
1949-03         132
1949-04         129
1949-05         121
...             ...
1960-08         606
1960-09         508
1960-10         461
1960-11         390
1960-12         432

[144 rows x 1 columns]

In [13]:
def split_xy1(dataset, time_steps):
    x, y = list(), list()
    for i in range(len(dataset)):
        end_number = i + time_steps
        if end_number > len(dataset) -1:
            break
        tmp_x, tmp_y = dataset[i:end_number], dataset[end_number]
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)

In [14]:
x, y = split_xy1( df2['passengers'].values, 3 )
print(x)
print('===============')
print(y)

[[112 118 132]
 [118 132 129]
 [132 129 121]
 [129 121 135]
 [121 135 148]
 [135 148 148]
 [148 148 136]
 [148 136 119]
 [136 119 104]
 [119 104 118]
 [104 118 115]
 [118 115 126]
 [115 126 141]
 [126 141 135]
 [141 135 125]
 [135 125 149]
 [125 149 170]
 [149 170 170]
 [170 170 158]
 [170 158 133]
 [158 133 114]
 [133 114 140]
 [114 140 145]
 [140 145 150]
 [145 150 178]
 [150 178 163]
 [178 163 172]
 [163 172 178]
 [172 178 199]
 [178 199 199]
 [199 199 184]
 [199 184 162]
 [184 162 146]
 [162 146 166]
 [146 166 171]
 [166 171 180]
 [171 180 193]
 [180 193 181]
 [193 181 183]
 [181 183 218]
 [183 218 230]
 [218 230 242]
 [230 242 209]
 [242 209 191]
 [209 191 172]
 [191 172 194]
 [172 194 196]
 [194 196 196]
 [196 196 236]
 [196 236 235]
 [236 235 229]
 [235 229 243]
 [229 243 264]
 [243 264 272]
 [264 272 237]
 [272 237 211]
 [237 211 180]
 [211 180 201]
 [180 201 204]
 [201 204 188]
 [204 188 235]
 [188 235 227]
 [235 227 234]
 [227 234 264]
 [234 264 302]
 [264 302 293]
 [302 293 

In [18]:
x = x.reshape(-1, 3, 1) # (batch size, sequence length, feature size)
x

array([[[112],
        [118],
        [132]],

       [[118],
        [132],
        [129]],

       [[132],
        [129],
        [121]],

       [[129],
        [121],
        [135]],

       [[121],
        [135],
        [148]],

       [[135],
        [148],
        [148]],

       [[148],
        [148],
        [136]],

       [[148],
        [136],
        [119]],

       [[136],
        [119],
        [104]],

       [[119],
        [104],
        [118]],

       [[104],
        [118],
        [115]],

       [[118],
        [115],
        [126]],

       [[115],
        [126],
        [141]],

       [[126],
        [141],
        [135]],

       [[141],
        [135],
        [125]],

       [[135],
        [125],
        [149]],

       [[125],
        [149],
        [170]],

       [[149],
        [170],
        [170]],

       [[170],
        [170],
        [158]],

       [[170],
        [158],
        [133]],

       [[158],
        [133],
        [114]],

       [[133]

In [19]:
model = Sequential()                    #sequence length, feature size
model.add( LSTM( 64, activation='relu', input_shape=(3, 1) ) )
model.add( Dense( units=32 ) )
model.add( Dense( units=1 ) )
model.compile( loss='mse', optimizer='adam' )
model.fit(x, y, epochs=1000)

Epoch 1/1000
5/5 [==============================] - 1s 2ms/step - loss: 109280.7969
Epoch 2/1000
5/5 [==============================] - 0s 2ms/step - loss: 91273.6250
Epoch 3/1000
5/5 [==============================] - 0s 2ms/step - loss: 73511.3906
Epoch 4/1000
5/5 [==============================] - 0s 2ms/step - loss: 56931.5820
Epoch 5/1000
5/5 [==============================] - 0s 2ms/step - loss: 39669.4648
Epoch 6/1000
5/5 [==============================] - 0s 2ms/step - loss: 21208.6035
Epoch 7/1000
5/5 [==============================] - 0s 2ms/step - loss: 6754.5991
Epoch 8/1000
5/5 [==============================] - 0s 2ms/step - loss: 3711.4727
Epoch 9/1000
5/5 [==============================] - 0s 2ms/step - loss: 3787.5146
Epoch 10/1000
5/5 [==============================] - 0s 2ms/step - loss: 2887.7109
Epoch 11/1000
5/5 [==============================] - 0s 2ms/step - loss: 2758.7947
Epoch 12/1000
5/5 [==============================] - 0s 2ms/step - loss: 2825.1233
Epoch 

5/5 [==============================] - 0s 2ms/step - loss: 1682.4033
Epoch 100/1000
5/5 [==============================] - 0s 2ms/step - loss: 1694.0560
Epoch 101/1000
5/5 [==============================] - 0s 2ms/step - loss: 1686.3596
Epoch 102/1000
5/5 [==============================] - 0s 2ms/step - loss: 1726.6012
Epoch 103/1000
5/5 [==============================] - 0s 2ms/step - loss: 1687.9629
Epoch 104/1000
5/5 [==============================] - 0s 2ms/step - loss: 1757.4930
Epoch 105/1000
5/5 [==============================] - 0s 2ms/step - loss: 1692.4290
Epoch 106/1000
5/5 [==============================] - 0s 2ms/step - loss: 1625.7428
Epoch 107/1000
5/5 [==============================] - 0s 2ms/step - loss: 1739.6088
Epoch 108/1000
5/5 [==============================] - 0s 2ms/step - loss: 1620.3418
Epoch 109/1000
5/5 [==============================] - 0s 2ms/step - loss: 1630.3861
Epoch 110/1000
5/5 [==============================] - 0s 2ms/step - loss: 1633.5645
Epoch 1

5/5 [==============================] - 0s 1ms/step - loss: 1348.3331
Epoch 197/1000
5/5 [==============================] - 0s 1ms/step - loss: 1322.9772
Epoch 198/1000
5/5 [==============================] - 0s 2ms/step - loss: 1338.9792
Epoch 199/1000
5/5 [==============================] - 0s 2ms/step - loss: 1507.6556
Epoch 200/1000
5/5 [==============================] - 0s 2ms/step - loss: 1479.3628
Epoch 201/1000
5/5 [==============================] - 0s 2ms/step - loss: 1397.7898
Epoch 202/1000
5/5 [==============================] - 0s 2ms/step - loss: 1815.6223
Epoch 203/1000
5/5 [==============================] - 0s 2ms/step - loss: 1511.4631
Epoch 204/1000
5/5 [==============================] - 0s 2ms/step - loss: 1481.8292
Epoch 205/1000
5/5 [==============================] - 0s 1ms/step - loss: 1378.7687
Epoch 206/1000
5/5 [==============================] - 0s 1ms/step - loss: 1256.5056
Epoch 207/1000
5/5 [==============================] - 0s 1ms/step - loss: 1348.2931
Epoch 2

5/5 [==============================] - 0s 2ms/step - loss: 1148.9081
Epoch 294/1000
5/5 [==============================] - 0s 1ms/step - loss: 1128.7424
Epoch 295/1000
5/5 [==============================] - 0s 1ms/step - loss: 1142.9833
Epoch 296/1000
5/5 [==============================] - 0s 2ms/step - loss: 1114.5922
Epoch 297/1000
5/5 [==============================] - 0s 2ms/step - loss: 1171.8237
Epoch 298/1000
5/5 [==============================] - 0s 2ms/step - loss: 1078.6088
Epoch 299/1000
5/5 [==============================] - 0s 2ms/step - loss: 1182.6609
Epoch 300/1000
5/5 [==============================] - 0s 2ms/step - loss: 1085.2572
Epoch 301/1000
5/5 [==============================] - 0s 1ms/step - loss: 1256.6650
Epoch 302/1000
5/5 [==============================] - 0s 1ms/step - loss: 1280.0280
Epoch 303/1000
5/5 [==============================] - 0s 2ms/step - loss: 1414.1555
Epoch 304/1000
5/5 [==============================] - 0s 2ms/step - loss: 1565.7137
Epoch 3

5/5 [==============================] - 0s 2ms/step - loss: 1260.5178
Epoch 391/1000
5/5 [==============================] - 0s 2ms/step - loss: 1112.3606
Epoch 392/1000
5/5 [==============================] - 0s 1ms/step - loss: 1112.3914
Epoch 393/1000
5/5 [==============================] - 0s 1ms/step - loss: 1104.3717
Epoch 394/1000
5/5 [==============================] - 0s 2ms/step - loss: 1093.4308
Epoch 395/1000
5/5 [==============================] - 0s 2ms/step - loss: 1081.0868
Epoch 396/1000
5/5 [==============================] - 0s 2ms/step - loss: 1184.3644
Epoch 397/1000
5/5 [==============================] - 0s 2ms/step - loss: 1125.5809
Epoch 398/1000
5/5 [==============================] - 0s 2ms/step - loss: 1100.5989
Epoch 399/1000
5/5 [==============================] - 0s 2ms/step - loss: 1143.7833
Epoch 400/1000
5/5 [==============================] - 0s 2ms/step - loss: 1159.7928
Epoch 401/1000
5/5 [==============================] - 0s 2ms/step - loss: 1078.5736
Epoch 4

5/5 [==============================] - 0s 2ms/step - loss: 1077.7637
Epoch 488/1000
5/5 [==============================] - 0s 2ms/step - loss: 1056.5375
Epoch 489/1000
5/5 [==============================] - 0s 2ms/step - loss: 1148.2671
Epoch 490/1000
5/5 [==============================] - 0s 2ms/step - loss: 1521.5134
Epoch 491/1000
5/5 [==============================] - 0s 2ms/step - loss: 1250.9662
Epoch 492/1000
5/5 [==============================] - 0s 2ms/step - loss: 1228.8535
Epoch 493/1000
5/5 [==============================] - 0s 2ms/step - loss: 1312.1471
Epoch 494/1000
5/5 [==============================] - 0s 2ms/step - loss: 1254.7822
Epoch 495/1000
5/5 [==============================] - 0s 2ms/step - loss: 1158.1656
Epoch 496/1000
5/5 [==============================] - 0s 2ms/step - loss: 1259.3993
Epoch 497/1000
5/5 [==============================] - 0s 2ms/step - loss: 1135.8456
Epoch 498/1000
5/5 [==============================] - 0s 2ms/step - loss: 1183.3450
Epoch 4

5/5 [==============================] - 0s 2ms/step - loss: 1231.7175
Epoch 585/1000
5/5 [==============================] - 0s 2ms/step - loss: 1263.2142
Epoch 586/1000
5/5 [==============================] - 0s 2ms/step - loss: 1192.9030
Epoch 587/1000
5/5 [==============================] - 0s 2ms/step - loss: 1112.6567
Epoch 588/1000
5/5 [==============================] - 0s 2ms/step - loss: 1300.2991
Epoch 589/1000
5/5 [==============================] - 0s 2ms/step - loss: 1179.9474
Epoch 590/1000
5/5 [==============================] - 0s 2ms/step - loss: 1082.3018
Epoch 591/1000
5/5 [==============================] - 0s 2ms/step - loss: 1210.9935
Epoch 592/1000
5/5 [==============================] - 0s 2ms/step - loss: 1116.1123
Epoch 593/1000
5/5 [==============================] - 0s 2ms/step - loss: 1124.3201
Epoch 594/1000
5/5 [==============================] - 0s 2ms/step - loss: 1102.4353
Epoch 595/1000
5/5 [==============================] - 0s 1ms/step - loss: 1108.2740
Epoch 5

5/5 [==============================] - 0s 2ms/step - loss: 1288.1013
Epoch 682/1000
5/5 [==============================] - 0s 2ms/step - loss: 1040.6018
Epoch 683/1000
5/5 [==============================] - 0s 2ms/step - loss: 1197.1029
Epoch 684/1000
5/5 [==============================] - 0s 2ms/step - loss: 1049.5913
Epoch 685/1000
5/5 [==============================] - 0s 2ms/step - loss: 1255.6697
Epoch 686/1000
5/5 [==============================] - 0s 2ms/step - loss: 1196.7960
Epoch 687/1000
5/5 [==============================] - 0s 2ms/step - loss: 1087.4017
Epoch 688/1000
5/5 [==============================] - 0s 2ms/step - loss: 1118.6995
Epoch 689/1000
5/5 [==============================] - 0s 2ms/step - loss: 1186.1630
Epoch 690/1000
5/5 [==============================] - 0s 2ms/step - loss: 1136.8416
Epoch 691/1000
5/5 [==============================] - 0s 2ms/step - loss: 1145.6361
Epoch 692/1000
5/5 [==============================] - 0s 2ms/step - loss: 1137.1136
Epoch 6

5/5 [==============================] - 0s 2ms/step - loss: 1049.6444
Epoch 779/1000
5/5 [==============================] - 0s 2ms/step - loss: 1067.5992
Epoch 780/1000
5/5 [==============================] - 0s 2ms/step - loss: 1068.0175
Epoch 781/1000
5/5 [==============================] - 0s 2ms/step - loss: 1021.9196
Epoch 782/1000
5/5 [==============================] - 0s 2ms/step - loss: 1032.0067
Epoch 783/1000
5/5 [==============================] - 0s 2ms/step - loss: 1116.8011
Epoch 784/1000
5/5 [==============================] - 0s 2ms/step - loss: 1107.8870
Epoch 785/1000
5/5 [==============================] - 0s 2ms/step - loss: 1034.1554
Epoch 786/1000
5/5 [==============================] - 0s 2ms/step - loss: 1154.6227
Epoch 787/1000
5/5 [==============================] - 0s 2ms/step - loss: 1080.1558
Epoch 788/1000
5/5 [==============================] - 0s 2ms/step - loss: 1047.3392
Epoch 789/1000
5/5 [==============================] - 0s 2ms/step - loss: 1123.0129
Epoch 7

5/5 [==============================] - 0s 2ms/step - loss: 1084.1201
Epoch 876/1000
5/5 [==============================] - 0s 1ms/step - loss: 1129.7858
Epoch 877/1000
5/5 [==============================] - 0s 2ms/step - loss: 1000.9180
Epoch 878/1000
5/5 [==============================] - 0s 2ms/step - loss: 1128.5798
Epoch 879/1000
5/5 [==============================] - 0s 2ms/step - loss: 1023.5505
Epoch 880/1000
5/5 [==============================] - 0s 2ms/step - loss: 1048.3529
Epoch 881/1000
5/5 [==============================] - 0s 2ms/step - loss: 994.1694
Epoch 882/1000
5/5 [==============================] - 0s 1ms/step - loss: 1121.5165
Epoch 883/1000
5/5 [==============================] - 0s 2ms/step - loss: 1038.0676
Epoch 884/1000
5/5 [==============================] - 0s 1ms/step - loss: 1057.3379
Epoch 885/1000
5/5 [==============================] - 0s 2ms/step - loss: 1133.5215
Epoch 886/1000
5/5 [==============================] - 0s 2ms/step - loss: 1049.3955
Epoch 88

Epoch 973/1000
5/5 [==============================] - 0s 1ms/step - loss: 942.1553
Epoch 974/1000
5/5 [==============================] - 0s 1ms/step - loss: 925.9470
Epoch 975/1000
5/5 [==============================] - 0s 2ms/step - loss: 943.0906
Epoch 976/1000
5/5 [==============================] - 0s 2ms/step - loss: 941.7842
Epoch 977/1000
5/5 [==============================] - 0s 1ms/step - loss: 948.4125
Epoch 978/1000
5/5 [==============================] - 0s 1ms/step - loss: 951.7650
Epoch 979/1000
5/5 [==============================] - 0s 1ms/step - loss: 952.8635
Epoch 980/1000
5/5 [==============================] - 0s 1ms/step - loss: 987.8395
Epoch 981/1000
5/5 [==============================] - 0s 1ms/step - loss: 944.8956
Epoch 982/1000
5/5 [==============================] - 0s 1ms/step - loss: 1039.6281
Epoch 983/1000
5/5 [==============================] - 0s 2ms/step - loss: 988.8653
Epoch 984/1000
5/5 [==============================] - 0s 2ms/step - loss: 1067.0806
Ep

In [20]:
#정규화 필요
model.predict( array([461, 360, 432]).reshape(1, 3, 1) )

array([[433.24133]], dtype=float32)

#### 3개의 타임스텝으로 rnn 학습하여 461, 360, 432인 경우의 2개의 예측값 구하기

In [34]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [35]:
scale = MinMaxScaler()
xN = scale.fit_transform( df2['passengers'].values.reshape(-1, 1))
xN

array([[0.01544402],
       [0.02702703],
       [0.05405405],
       [0.04826255],
       [0.03281853],
       [0.05984556],
       [0.08494208],
       [0.08494208],
       [0.06177606],
       [0.02895753],
       [0.        ],
       [0.02702703],
       [0.02123552],
       [0.04247104],
       [0.07142857],
       [0.05984556],
       [0.04054054],
       [0.08687259],
       [0.12741313],
       [0.12741313],
       [0.1042471 ],
       [0.05598456],
       [0.01930502],
       [0.06949807],
       [0.07915058],
       [0.08880309],
       [0.14285714],
       [0.11389961],
       [0.13127413],
       [0.14285714],
       [0.18339768],
       [0.18339768],
       [0.15444015],
       [0.11196911],
       [0.08108108],
       [0.11969112],
       [0.12934363],
       [0.14671815],
       [0.17181467],
       [0.14864865],
       [0.15250965],
       [0.22007722],
       [0.24324324],
       [0.26640927],
       [0.2027027 ],
       [0.16795367],
       [0.13127413],
       [0.173

In [27]:
def split_xy2(dataset, time_steps, y_column):
    x, y = list(), list()
    for i in range(len(dataset)):
        x_end_number = i + time_steps
        y_end_number = x_end_number + y_column # 추가
        # if end_number > len(dataset) -1:
        # break
        if y_end_number > len(dataset): # 수정
            break
        tmp_x = dataset[i : x_end_number]
        tmp_y = dataset[x_end_number : y_end_number] # 수정
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)

In [36]:
x, y = split_xy2( xN, 3, 2 )
print(x)
print('===============')
print(y)

[[[0.01544402]
  [0.02702703]
  [0.05405405]]

 [[0.02702703]
  [0.05405405]
  [0.04826255]]

 [[0.05405405]
  [0.04826255]
  [0.03281853]]

 [[0.04826255]
  [0.03281853]
  [0.05984556]]

 [[0.03281853]
  [0.05984556]
  [0.08494208]]

 [[0.05984556]
  [0.08494208]
  [0.08494208]]

 [[0.08494208]
  [0.08494208]
  [0.06177606]]

 [[0.08494208]
  [0.06177606]
  [0.02895753]]

 [[0.06177606]
  [0.02895753]
  [0.        ]]

 [[0.02895753]
  [0.        ]
  [0.02702703]]

 [[0.        ]
  [0.02702703]
  [0.02123552]]

 [[0.02702703]
  [0.02123552]
  [0.04247104]]

 [[0.02123552]
  [0.04247104]
  [0.07142857]]

 [[0.04247104]
  [0.07142857]
  [0.05984556]]

 [[0.07142857]
  [0.05984556]
  [0.04054054]]

 [[0.05984556]
  [0.04054054]
  [0.08687259]]

 [[0.04054054]
  [0.08687259]
  [0.12741313]]

 [[0.08687259]
  [0.12741313]
  [0.12741313]]

 [[0.12741313]
  [0.12741313]
  [0.1042471 ]]

 [[0.12741313]
  [0.1042471 ]
  [0.05598456]]

 [[0.1042471 ]
  [0.05598456]
  [0.01930502]]

 [[0.05598456

In [37]:
x.shape

(140, 3, 1)

In [38]:
model = Sequential()                    #sequence length, feature size
model.add( LSTM( 64, activation='relu', input_shape=(3, 1) ) )
model.add( Dense( units=32 ) )
model.add( Dense( units=2 ) )
model.compile( loss='mse', optimizer='adam' )
model.fit(x, y, epochs=1000)

Epoch 1/1000
5/5 [==============================] - 1s 2ms/step - loss: 0.1570
Epoch 2/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.1192
Epoch 3/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0838
Epoch 4/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0554
Epoch 5/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0332
Epoch 6/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0239
Epoch 7/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0246
Epoch 8/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0254
Epoch 9/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0224
Epoch 10/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0193
Epoch 11/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0182
Epoch 12/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0168
Epoch 13/1000
5/5 [==============================

5/5 [==============================] - 0s 2ms/step - loss: 0.0061
Epoch 104/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0063
Epoch 105/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0062
Epoch 106/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0063
Epoch 107/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0060
Epoch 108/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0066
Epoch 109/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0063
Epoch 110/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0063
Epoch 111/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0064
Epoch 112/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0061
Epoch 113/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0063
Epoch 114/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0062
Epoch 115/1000
5/5 [=======================

5/5 [==============================] - 0s 2ms/step - loss: 0.0057
Epoch 205/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0057
Epoch 206/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0057
Epoch 207/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0057
Epoch 208/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0057
Epoch 209/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0057
Epoch 210/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0057
Epoch 211/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0059
Epoch 212/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0060
Epoch 213/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0057
Epoch 214/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0059
Epoch 215/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0058
Epoch 216/1000
5/5 [=======================

5/5 [==============================] - 0s 1ms/step - loss: 0.0053
Epoch 306/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0053
Epoch 307/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0060
Epoch 308/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0055
Epoch 309/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0056
Epoch 310/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0057
Epoch 311/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0053
Epoch 312/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0052
Epoch 313/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0057
Epoch 314/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0053
Epoch 315/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0053
Epoch 316/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0052
Epoch 317/1000
5/5 [=======================

5/5 [==============================] - 0s 2ms/step - loss: 0.0051
Epoch 407/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0050
Epoch 408/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0051
Epoch 409/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0049
Epoch 410/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0050
Epoch 411/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0050
Epoch 412/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0050
Epoch 413/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0051
Epoch 414/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0051
Epoch 415/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0050
Epoch 416/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0050
Epoch 417/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0049
Epoch 418/1000
5/5 [=======================

5/5 [==============================] - 0s 2ms/step - loss: 0.0047
Epoch 508/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0048
Epoch 509/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0048
Epoch 510/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0048
Epoch 511/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0047
Epoch 512/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0048
Epoch 513/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0047
Epoch 514/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0047
Epoch 515/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0049
Epoch 516/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0047
Epoch 517/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0047
Epoch 518/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0049
Epoch 519/1000
5/5 [=======================

5/5 [==============================] - 0s 2ms/step - loss: 0.0045
Epoch 609/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0047
Epoch 610/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0047
Epoch 611/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0045
Epoch 612/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0046
Epoch 613/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0046
Epoch 614/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0044
Epoch 615/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0045
Epoch 616/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0045
Epoch 617/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0047
Epoch 618/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0043
Epoch 619/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0049
Epoch 620/1000
5/5 [=======================

5/5 [==============================] - 0s 2ms/step - loss: 0.0043
Epoch 710/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0044
Epoch 711/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0042
Epoch 712/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0043
Epoch 713/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0042
Epoch 714/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0043
Epoch 715/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0044
Epoch 716/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0043
Epoch 717/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0044
Epoch 718/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0045
Epoch 719/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0047
Epoch 720/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0044
Epoch 721/1000
5/5 [=======================

5/5 [==============================] - 0s 2ms/step - loss: 0.0040
Epoch 811/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0044
Epoch 812/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0046
Epoch 813/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0041
Epoch 814/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0044
Epoch 815/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0044
Epoch 816/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0049
Epoch 817/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0046
Epoch 818/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0042
Epoch 819/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0043
Epoch 820/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0046
Epoch 821/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0040
Epoch 822/1000
5/5 [=======================

5/5 [==============================] - 0s 2ms/step - loss: 0.0039
Epoch 912/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0039
Epoch 913/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0041
Epoch 914/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0039
Epoch 915/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0039
Epoch 916/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0040
Epoch 917/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0039
Epoch 918/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0039
Epoch 919/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0039
Epoch 920/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0039
Epoch 921/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0039
Epoch 922/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0039
Epoch 923/1000
5/5 [=======================

In [42]:
pd = scale.transform( array([461, 360, 432]).reshape(-1, 1) ).reshape(1, 3, 1)

In [44]:
p = model.predict( pd )
scale.inverse_transform(p)

array([[389.23578, 379.0379 ]], dtype=float32)